---
title: "1_Diagnostics_DEG_Notebook"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
# ICM 2024MAY15 DESeq2 Script
# UM v IM v H

```{r CODE CHUNK 1 CLEAR}
# Clean environment
rm (list = ls (all.names = TRUE)) # will clear all objects including hidden objects
gc () # free up memory and report the memory usage
options (max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and keep scientific notation
```


```{r CHUNK 2 INSTALLING}
# Remove hashtags to install any missing packages
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("escape")

#Install all
#BiocManager::install(c( "corrplot", "dendextend","readr","DESeq2", "ggrepel", "ggplot2", "pheatmap", "devtools", "ggforce","pheatmap", "gplots", "RColorBrewer", "ggdendro","enrichplot", "magrittr","dplyr","tibble", "tidyverse", "ComplexHeatmap", "escape")) 

#install one
#BiocManager::install(c("dendsort"))

```


```{r CHUNK 3 Loading packages}
# Load necessary packages
suppressPackageStartupMessages({
  library(DESeq2)
  library(readr)
  library(tidyverse)
  library(enrichplot)
  library(dplyr)
  library(tibble)
  library(magrittr)
  library(gplots)
  library(RColorBrewer)
  library(corrplot)
  library(ggdendro)
  library(dendextend)
  library(ggplot2)
  library(ggrepel)
  library(pheatmap)
  library(escape)
  library(clusterProfiler)
  library(org.At.tair.db)
})

```


```{r CHUNK Set the working directory to your project folders}
# Set the working directory to your project folder
setwd("~/Desktop/Lab/Working_Projects/R_trapseq_2023")
```


```{r CHUNK 4 Set Up Raw Counts}
# Read in raw count data
featcount <- read_table("./RawData/featcount.txt", col_names = TRUE, skip = 1)
read.count <- data.frame(featcount, row.names = featcount$Geneid)  # Set gene IDs as row names
read.count <- read.count[, -c(1:6)]  # Remove columns not related to gene counts
```


```{r CHUNK 5 Modify Data}
# Rename columns for consistency
orig_names <- names(read.count)  # Backup original names
colnames(read.count) <- c("IT-107", "IT-108", "IT-109", "IT-110", "H-107", "H-108", "H-109", "H-110", "H-111", "UT-106", "UT-108", "UT-114", "IT-206", "IT-207", "IT-208", "IT-209", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UT-204", "UT-208", "UT-213", "UT-214", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215")
```


```{r Minus Outliers CHUNK 5.1}
######  DEFINING CONDITIONS WE WANT TO WORK WITH
#ImvHvUM <- read.count [ ,-c(1:4,10:16,18,21,22:25)]
#write.csv ("./DerivedData/1_deg_countMatrix.csv") #remove hashtag to save the new count data file

#without IM 207 + 210
#Match the samples to the variable. Don't need to change this unless you want to add variables.
#sample_info <- data.frame(
#  sample = c( "H-107", "H-108", "H-109", "H-110","H-111","IM-206", "IM-208", "IM-209", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215" ),
#  groups = c( "H", "H", "H", "H","H", "IM", "IM", "IM","UM","UM","UM","UM","UM"),
#  condition = c ("Infected","Infected","Infected","Infected","Infected","Infected","Infected","Infected", "Uninfected","Uninfected","Uninfected","Uninfected","Uninfected"),
#  replicate = c("H-107", "H-108", "H-109", "H-110","H-111", "IM-206",  "IM-208", "IM-209","UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
#  row.names = "sample")
```

```{r CHUNK 6 Set Variables}
#Removing the data we are not using and writing the raw count data to a new file. 
ImvHvUM <- read.count [ ,-c(1:4,10:16,22:25)]

#Variables
sample_info <- data.frame(
  Sample = c( "H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  Groups = c( "H", "H", "H", "H", "H", "IM", "IM", "IM", "IM", "IM", "UM", "UM", "UM", "UM", "UM"),
  Condition = c("Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Uninfected", "Uninfected", "Uninfected", "Uninfected", "Uninfected"),
  Replicate = c("H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  row.names = "Sample") 

sample_info$Groups <- as.factor (sample_info$Groups)
all (rownames (sample_info) %in% colnames (ImvHvUM)) #if "false" something is wrong
#sample_info 
```


```{r CHUNK 6.1 IM V H}
ImvH <- read.count [ ,-c(1:4,10:16,22:30)]

#Variables
sample_info <- data.frame(
  sample = c( "H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210"),
  Groups = c( "H", "H", "H", "H", "H", "IM", "IM", "IM", "IM", "IM"),
  condition = c("Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected"),
  replicate = c("H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210"),
  row.names = "sample") 

sample_info$Groups <- as.factor (sample_info$Groups)
all (rownames (sample_info) %in% colnames (ImvH)) #if "false" something is wrong
sample_info
```


```{r CODE CHUNK 7 Matrix}
# Create DESeq2 dataset
dds <- DESeqDataSetFromMatrix (countData = ImvHvUM, 
                               colData = sample_info, 
                               design = ~ Groups)

# Prefilter: remove genes with less than 10 counts across all samples
dds <- dds [rowSums (counts (dds)) > 10, ]

# Set control group for comparisons
dds$groups <- relevel (dds$Groups, ref = "UM")

```


```{r}
# Plot expression for a single gene (example: AT1G09380)
d <- plotCounts (dds, 
                 gene = "AT1G09380", 
                 intgroup = "Groups", 
                 returnData = TRUE)

# Create plot with jittered points and gene labels
ggplot (d, aes (x = Groups, y = count, color = Groups)) +
  geom_point (position = position_jitter (w = 0.1, h = 0)) +
  geom_text_repel (aes (label = rownames (d))) +
  theme_bw () +
  ggtitle ("AT1G09380 Expression") +
  theme (plot.title = element_text (hjust = 0.5))
#ggsave("./SumData/1_countData_AT1G09380.pdf")
```


```{r CODE CHUNK 8 Normalization}
# Perform variance stabilizing transformation (VST) for visualization and clustering
vsd <- vst (dds)
colnames (vsd) <- sample_info$Replicate
norm.counts <- assay (vsd)

```


```{r CODE CHUNK 9 PCA}
library(ggrepel)
# PCA principle component analysis, visualize the similarities and differences between *samples*
pcadata <- plotPCA (vsd, intgroup = c( "Replicate" , "Groups" ), returnData = TRUE) 
#summary(pcadata)

percentVar <- round (100 * attr (pcadata, "percentVar" ))

p <- ggplot (pcadata, aes(PC1, PC2, label = Replicate, colour = Groups)) +
  geom_point (aes (shape = Groups), size = 4) + scale_color_manual (values = c( "#FF1BB3", "#E5751F", "#861F41" )) +
   theme_classic()

p2 <- p + geom_text_repel (box.padding = 1, cex = 3, max.overlaps = 30, segment.linetype = 2) + labs (title = "PCA of VST Normalized Gene Counts" ) +
  xlab(paste0 ( "PC1: ", percentVar[1], "% variance" )) +
  ylab(paste0 ( "PC2: ", percentVar[2], "% variance" ))
p2
#ggsave("./SumData/1_PCA_Final_IMVUMVH_v2.pdf")  #edit and uncheck to save graph to your chosen spot
```


```{r CODE CHUNK 10 Sample Distances}
# Calculate sample distances and create hierarchical clustering
norm.counts <- norm.counts [complete.cases (norm.counts), ]
normcorr <- cor (norm.counts, method = "spearman")
distance.m <- as.dist (1 - normcorr)

# Hierarchical clustering
hc <- hclust (distance.m, method = "complete")
hcd <- as.dendrogram (hc) %>% color_branches (k = 2)

# Plot dendrogram
plot (hcd, type = "rectangle", ylab = "Height", main = "VST Read Counts - Distance: Spearman Correlation")
#ggsave("./SumData/1_Dendogram_v2.pdf")

# Create heatmap of the distance matrix
DistMatrix <- as.matrix (distance.m)
rownames (DistMatrix) <- paste (vsd$replicate, sep = "-")
colnames (DistMatrix) <- paste (vsd$replicate, sep = "-")
colors <- colorRampPalette (rev (brewer.pal (9, "Blues")))(255)

pheatmap (DistMatrix, clustering_distance_rows = distance.m, clustering_distance_cols = distance.m, 
         color = colors, main = "Sample Distance Matrix Heatmap")
#ggsave("./SumData/1_distmatrix_v2.pdf")

```


```{r CODE CHUNK 11 Run Deseq2}
# Code Chunk 11: Run DESeq2 Differential Expression Analysis
dds$Groups <- relevel (dds$Groups, ref = "UM")  # Set reference group to "UM"
dds.ds <- DESeq(dds)  # Perform differential expression analysis
res <- results(dds.ds)  # Extract results
# write.csv(res, file = "./DerivedData/1_RES_HvIMvUM_v1.csv", quote = FALSE, row.names = TRUE)
```


```{r}
pad <- 0.05
UMvsH <- results (dds.ds, c( "Groups", "H", "UM" ))

# Map TAIR IDs to ENTREZ IDs
UMvsH$entrez <- mapIds (org.At.tair.db, 
                        keys = row.names (UMvsH), 
                        keytype = "TAIR", 
                        column = "ENTREZID", 
                        multiVals = "first")

H_DF <- UMvsH %>% 
  as.data.frame() %>%
  rownames_to_column (., var = "rowname") %>%
  as_tibble() %>% 
  na.omit()
# write.csv(H_DF, file = "./DerivedData/1_DEG_H_HvUM_v2.csv", quote = FALSE, row.names = TRUE)
 
H_DEG_table <- H_DF %>% 
  mutate (diffexpressed = case_when (
  log2FoldChange > 0 &   padj < pad ~ 'H_UP',
  log2FoldChange < 0 &   padj < pad ~ 'H_DOWN',
  padj > pad ~ 'NO' ))

H_DEG_table <- H_DEG_table [H_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes
# Substitute names so they are annotated nicely in the heatmap later
unique (H_DEG_table$diffexpressed)

# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
H_results_split <- split (H_DEG_table, H_DEG_table$diffexpressed)

HDOWN <- c (H_results_split$H_DOWN)
HDOWN <- as.data.frame (HDOWN, row.names = HDOWN$entrez)
write.csv(HDOWN, file = "./DerivedData/1_DEG_H_DOWN_HvUM_v1.csv", quote = FALSE, row.names = TRUE)
 
HUP <- c (H_results_split$H_UP)
HUP <- as.data.frame(HUP, row.names = HUP$entrez)
 write.csv(HUP, file = "./DerivedData/1_DEG_H_UP_HvUM_v1.csv", quote = FALSE, row.names = TRUE)
```

```{r}
UMVsIM <- results (dds.ds, c('Groups', 'IM', 'UM'))

# Map TAIR IDs to ENTREZ IDs
UMVsIM$entrez <- mapIds(org.At.tair.db, keys = row.names(UMVsIM), keytype = "TAIR", column = "ENTREZID", multiVals = "first")

IM_DF <- UMVsIM %>% 
  as.data.frame() %>%
  rownames_to_column (., var = "rowname") %>%
  as_tibble() %>% 
  na.omit()
 write.csv(IM_DF, file = "./DerivedData/1_DEG_IM_IMvUM_v2.csv", quote = FALSE, row.names = TRUE)
 
IM_DEG_table <- IM_DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 0 &   padj < pad ~ 'IM_UP',
  log2FoldChange < 0 &   padj < pad ~ 'IM_DOWN',
  padj > pad ~ 'NO' ))

IM_DEG_table <- IM_DEG_table [IM_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heatmap later
unique (IM_DEG_table$diffexpressed)

# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
IM_results_split <- split (IM_DEG_table, IM_DEG_table$diffexpressed)

IMDOWN<- c(IM_results_split$IM_DOWN)
IMDOWN<-as.data.frame(IMDOWN, row.names = IMDOWN$entrez)

IMUP<- c(IM_results_split$IM_UP)
IMUP<-as.data.frame(IMUP, row.names = IMUP$entrez)
```

```{r}
pad <- 0.05
HVsIM <- results (dds.ds, contrast = c('Groups', 'H', 'IM'))

HVsIM$entrez = mapIds (org.At.tair.db, keys = row.names (HVsIM) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

DF <- HVsIM %>% 
  as.data.frame() %>%
  rownames_to_column (., var = "rowname") %>%
  as_tibble() %>% 
  na.omit() 
# write.csv(DF, file = "./DerivedData/1_DEG_H_HvIM_v1.csv", quote = FALSE, row.names = TRUE)
 
DEG_table <- DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 0 &   padj < pad ~ 'UP',
  log2FoldChange < 0 &   padj < pad ~ 'DOWN',
  padj > pad ~ 'NO' ))

DEG_table <- DEG_table [DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heatmap later
unique (DEG_table$diffexpressed)
## write.csv(DEG_table, file = "./DerivedData/1_DEG_H_HvIM_v1.csv", quote = FALSE, row.names = TRUE)
# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
DEG_table_split <- split (DEG_table, DEG_table$diffexpressed)

DFDOWN<- c(DEG_table_split$DOWN)
DFDOWN<-as.data.frame(DFDOWN, row.names = DFDOWN$entrez)
#write.csv(DFDOWN, file = "./DerivedData/1_DEG_H_DOWN_HvIMonly_v3.csv", quote = FALSE, row.names = TRUE)

DFUP<- c(DEG_table_split$UP)
DFUP<-as.data.frame(DFUP, row.names = DFUP$entrez)
#write.csv(DFUP, file = "./DerivedData/1_DEG_H_UP_HvIMonly_v3.csv", quote = FALSE, row.names = TRUE)
```
```{r}
test2<-c("AT1G58360","AT5G09220","AT1G77380","AT5G63850","AT1G44100","AT5G49630","AT3G04060","AT4G12490","AT1G73260","AT1G09932","AT1G14870","AT4G14630", "AT5G24530", "AT3G49780", "AT4G31800", "AT1G22150", "AT1G77990", "AT1G23090", "AT1G78000", "AT3G12520", "AT3G15990", "AT3G51895", "AT4G02700", "AT4G08620", "AT5G10180", "AT5G13550")



# Extract Gene Names with the desired adjusted p-value cut-off


# extract the normalized read counts for DE genes into a matrix
hm.mat_DGEgenes <- IM_DEG_table$rowname [test4 , ]
```


```{r}
#UP
# Remove rows with NA values in the 'entrez' column
#res_clean <- IMDOWN[!is.na(IMDOWN$entrez), ] #1
#res_clean <- HDOWN[!is.na(HDOWN$entrez), ] #2
res_clean <- DFDOWN[!is.na(DFDOWN$entrez), ]#3

# Remove rows with NA values in the 'entrez' column
#res_clean <- IMUP[!is.na(IMUP$entrez), ]
#res_clean <- HUP[!is.na(HUP$entrez), ]
#res_clean <- DFUP[!is.na(DFUP$entrez), ]

# Create a new table with ENTREZ IDs as row names and the matching log2FoldChange values
logfc_table <- data.frame(log2FoldChange = res_clean$log2FoldChange)
rownames(logfc_table) <- res_clean$entrez

# View the new table
head(logfc_table)

# Sort the gene list by decreasing log fold change
logfc_table_sorted <- logfc_table[order(logfc_table$log2FoldChange, decreasing = TRUE), , drop = FALSE]

# Convert log2FoldChange to a named numeric vector with ENTREZ IDs as names
gene_list <- setNames(logfc_table$log2FoldChange, rownames(logfc_table))

# Sort the gene list by decreasing log2FoldChange
gene_list_sorted3 <- sort(gene_list, decreasing = TRUE)


# View the first few entries of the sorted list
#head(H_gene_list_sorted)

```



```{r}
# Perform Gene Set Enrichment Analysis (GSEA) using GO terms
gse3 <- gseGO( #change num
  geneList = gene_list_sorted3, #change num
  ont = "ALL",
  minGSSize = 3,
  maxGSSize = 800,
  pvalueCutoff = 0.05,
  nPermSimple = 10000,
  verbose = TRUE,
  OrgDb = org.At.tair.db,
  pAdjustMethod = "none"
)
#ptgse1 <- pairwise_termsim(gse1)
#ptgse2 <- pairwise_termsim(gse2)
ptgse3 <- pairwise_termsim(gse3)
```

```{r}
# Visualization of GO enrichment results
require(DOSE)
mlist <- list (gse1, gse2 ,gse3)
names(mlist) <- c("IM DOWN IMvUM", "H DOWN HvUM", "HvIM DOWN")
mresult <- merge_result(mlist)

dotplot(gse3, showCategory = 15, font.size=14) + ggtitle("H Down Regulated Gene Enrichment")
ggsave("./SumData/1_DOT_HDOWN_HvIM.pdf", width=14, height =14)
```


```{r}
require(DOSE)
# Calculate term similarity and plot results
ptmlist <- list (ptgse1, ptgse2 ,ptgse3)
names(ptmlist) <- c("IM DOWN IMvUM", "H DOWN IMvUM", "HvIM DOWN")
prmresult <- merge_result(ptmlist)


dotplot(ptgse3, showCategory = 10, font.size=14) + ggtitle("Down Regulated Gene Enrichment")
ggsave("./SumData/1_DOT_PairedTerms_HDOWN_HvIM.pdf", width=14, height =14)
```


```{r}
emapplot(ptgse1, showCategory = 10,color = "p.adjust", layout = "grid", repel = TRUE)
#ggsave("./SumData/1_test2.pdf")
emapplot(ptgse2,  showCategory = 10,color = "p.adjust", layout = "grid", repel = TRUE)
emapplot(ptgse3,  showCategory = 10,color = "p.adjust", layout = "grid", repel = TRUE)
```
```{r}
cnetplot(ptgse1, 
         categorySize = "p.adjust", 
         showCategory = 20,
         layout = "kk",
         node_label = "category",
         shadowtext = "all",
         color.params = list(foldChange = gene_list_sorted1, 
                             edge = FALSE, #colors the lines by enrichment
                             category = "yellow", 
                             gene = "black"),
         cex.params = list(category_node = 1, 
                           gene_node = 1, 
                           category_label = 1, 
                           gene_label = 1),
         hilight.params = list(category = NULL, 
                               alpha_hilight = 1, 
                               alpha_no_hilight = 0.3))
#ggsave("./SumData/1_cnetplot_v1.pdf")

cnetplot(ptgse2, 
         categorySize = "p.adjust", 
         showCategory = 10,
         layout = "kk",
         node_label = "category",
         shadowtext = "all",
         color.params = list(foldChange = gene_list_sorted2, 
                             edge = FALSE, #colors the lines by enrichment
                             category = "yellow", 
                             gene = "black"),
         cex.params = list(category_node = 1, 
                           gene_node = 1, 
                           category_label = 1, 
                           gene_label = 1),
         hilight.params = list(category = NULL, 
                               alpha_hilight = 1, 
                               alpha_no_hilight = 0.3))
#ggsave("./SumData/1_cnetplot_HDown_HvUM_v1.pdf")

cnetplot(ptgse3, 
         categorySize = "p.adjust", 
         showCategory = 10,
         layout = "kk",
         node_label = "category",
         shadowtext = "all",
         color.params = list(foldChange = gene_list_sorted3, 
                             edge = FALSE, #colors the lines by enrichment
                             category = "yellow", 
                             gene = "black"),
         cex.params = list(category_node = 1, 
                           gene_node = 1, 
                           category_label = 1, 
                           gene_label = 1),
         hilight.params = list(category = NULL, 
                               alpha_hilight = 1, 
                               alpha_no_hilight = 0.3))
#ggsave("./SumData/1_Cnetplot_HDown_HvIM_v1.pdf")
```


```{r}
cnetplot(prmresult, 
         categorySize = "p.adjust", 
         showCategory = 2,
         layout = "kk",
         node_label = "category",
         shadowtext = "category",
         color.params = list(foldChange = NULL, 
                             edge = TRUE, 
                             category = "#E5C494", 
                             gene = "#B3B3B3"),
         cex.params = list(category_node = 1, 
                           gene_node = 1, 
                           category_label = 1, 
                           gene_label = 1),
         hilight.params = list(category = NULL, 
                               alpha_hilight = 1, 
                               alpha_no_hilight = 0.3))
#ggsave("./SumData/1_Cnetplot_v1.pdf", width=14, height =14)
```



```{r}
ridgeplot(ptgse1, 
          showCategory = 20,
          fill = "p.adjust",
          label_format = 30,
          orderBy = "NES") + 
  ggtitle("IM DOWN IMvUM LFC Distribution Within Categories")
#ggsave("./SumData/1_ridgeplot_IMvUM_IMDOWN_v1.pdf", width=14, height =14)


ridgeplot(ptgse2, 
          showCategory = 20,
          fill = "p.adjust",
          label_format = 30,
          orderBy = "NES") + 
          ggtitle("H DOWN HvUM LFC Distribution Within Categories")
#ggsave("./SumData/1_Ridgeplot_HDOWN_HvUM_v1.pdf", width=14, height =14)
          
ridgeplot(ptgse3, 
          showCategory = 20,
          fill = "p.adjust",
          label_format = 30,
          orderBy = "NES") + 
          ggtitle("HvIM DOWN LFC Distribution Within Categories")
#ggsave("./SumData/1_Ridgeplot_HDown_HvIM_v1.pdf", width=14, height =14)
```


```{r}
p1<- heatplot(ptgse1, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted1,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous(low="blue", 
                        high="red", 
                        name = "Fold Change") + 
  theme(panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 1),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 12))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("IM DOWN IMvUM GENE LFC Distribution Within Categories")
p2 
#ggsave("./SumData/1_Heatplot_IMvUM_IMDOWN_v1.pdf", width=14, height =14)

p1<- heatplot(ptgse2, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted2,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous(low="blue", 
                        high="red", 
                        name = "Fold Change") + 
  theme(panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 1),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 12))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("H DOWN HvUM GENE LFC Distribution Within Categories")
p2 
#ggsave("./SumData/1_HeatPlot_HDOWN_HvUM_v1.pdf", width=14, height =14)


p1<- heatplot(ptgse3, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted3,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous(low="blue", 
                        high="red", 
                        name = "Fold Change") + 
  theme(panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 1),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 12))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("H DOWN HvIM GENE LFC Distribution Within Categories")
p2 
ggsave("./SumData/1_Heatplot_HDown_HvIM_v1.pdf", width=14, height =14)
```


```{r}
ssplot(ptgse1,
       showCategory = 20, 
       split = "category",
cex_pie2axis = 0.0125,
dr.params = "all",
group_category = TRUE,
node_label = "all")
ggsave("./SumData/1_IMvUM_IMDOW_ssplot_v1.pdf", width=14, height =14)
```


```{r}
treeplot(ptgse1,
         showCategory = 10,
         color = "p.adjust",
         nWords = 3,
         label_format = 2,
         fontsize = 4,
         hclust_method = "complete",
         align = "both",
         hilight.params = list(hilight = TRUE, align = "both"),
         offset.params = list(bar_tree = rel(1), tiplab = rel(1), extend = 0.3,
                              hexpand = 0.1),
         cluster.params = list(method = "complete", color = NULL, label_words_n = 4,
label_format = 3))

treeplot(ptgse2,
         showCategory = 10,
         color = "p.adjust",
         nWords = 3,
         label_format = 2,
         fontsize = 4,
         hclust_method = "complete",
         align = "both",
         hilight.params = list(hilight = TRUE, align = "both"),
         offset.params = list(bar_tree = rel(1), tiplab = rel(1), extend = 0.3,
                              hexpand = 0.1),
         cluster.params = list(method = "complete", color = NULL, label_words_n = 4,
label_format = 3))
```


```{r}
upsetplot(ptgse1, n=5)
```


```{r}
# KEGG pathway analysis
require(clusterProfiler)
require(readr)
require(tidyverse)
require(pathview)
require(enrichplot)

pad <- 0.05
search_kegg_organism('ath', by = 'kegg_code')
search_kegg_organism('Arabidopsis thaliana', by = 'scientific_name')

# Perform GSEA with KEGG data
kk2 <- gseKEGG(
  geneList = IM_gene_list_sorted,
  organism = "ath",
  nPerm = 1000,
  minGSSize = 3,
  maxGSSize = 800,
  pvalueCutoff = 0.05,
  keyType = "ncbi-geneid",
  use_internal_data = FALSE
)

```

```{r}
# Visualize KEGG pathway enrichment results
require(DOSE)
dotplot(kk2, showCategory = 8, split = ".sign") + facet_grid(. ~ .sign) + ggtitle("KEGG Pathway Enrichment")
#ggsave("./SumData/1_test5.pdf")
kk2 <- pairwise_termsim(kk2)

emapplot(kk2, showCategory = 10)
#ggsave("./SumData/1_test6.pdf")
cnetplot(kk2, categorySize = "pvalue", foldChange = gene_list, showCategory = 3)
#ggsave("./SumData/1_test7.pdf")
ridgeplot(kk2) + labs(x = "Enrichment Distribution")
#ggsave("./SumData/1_test8.pdf")

```



```{r CODE CHUNK 12 Differentially Expressed Genes}
set.seed(123)
#Extract genes with LFC +- 1 and p.value of 0.05
Diff_genes_res = res %>%
   as.data.frame() %>%
   filter (padj < 0.05) %>%
  filter (abs (log2FoldChange) >= 1) #%>% write.csv("./DerivedData/1_DEG_HvIMvUM_padj05LCF1.csv") 

#Order genes by p.value
DGE.results.sorted <- Diff_genes_res [order (Diff_genes_res$padj), ]

# Extract Gene Names with the desired adjusted p-value cut-off
DGEgenes <- rownames (subset (DGE.results.sorted , padj < 0.05))


# extract the normalized read counts for DE genes into a matrix
hm.mat_DGEgenes <- norm.counts [DGEgenes , ]

# plot the normalized read counts of DE genes sorted by the adjusted p-value
#don't change this is final
set.seed(123)
k <- pheatmap (hm.mat_DGEgenes, show_rownames = FALSE, angle_col = c( "45" ), color = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu")))(100), 
            cluster_rows = TRUE,
            clustering_distance_rows = "correlation", 
            cluster_cols = TRUE,
            clustering_distance_cols = "correlation", 
            clustering_method = "complete", 
            scale = "row", cutree_cols = 2, 
            #cutree_rows = 2, 
          #  kmeans_k = 2
  )
#dev.copy2pdf(file="./SumData/1_hmap_IMvHvUM_official1.pdf")
```

```{r}
# Average normalized read counts for different conditions
Havg <- as.data.frame(hm.mat_DGEgenes[, c("H-107", "H-108", "H-109", "H-110", "H-111")])
IMavg <- as.data.frame(hm.mat_DGEgenes[, c("IM-206", "IM-207", "IM-208", "IM-209", "IM-210")])
UMavg <- as.data.frame(hm.mat_DGEgenes[, c("UM-204", "UM-208", "UM-213", "UM-214", "UM-215")])
H_means <- rowMeans(Havg)
IM_means <- rowMeans(IMavg)
UM_means <- rowMeans(UMavg)

mlist <- cbind(H_means, IM_means, UM_means) %>% as.data.frame()
set.seed(123)
pheatmap::pheatmap(
  mlist,
  show_rownames = TRUE,
  angle_col = 45,
  color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(100),
  cluster_rows = TRUE,
  clustering_distance_rows = "correlation",
  cluster_cols = TRUE,
  clustering_distance_cols = "correlation",
  clustering_method = "complete",
  scale = "row",
  kmeans_k = 4
)
# dev.copy2pdf(file = "./SumData/1_hmap_av_clustering_IMvHvUM_v2.pdf")

```


```{r}
# Cluster analysis
set.seed(123)
names(k$kmeans)
str(k)

clusterDF <- as.data.frame(factor(k$kmeans$cluster))
colnames(clusterDF) <- "Cluster"
clusterDF[1:10, , drop = FALSE]
OrderByCluster <- clusterDF %>% arrange(Cluster)

```


```{r}
module_df <- data.frame(
  gene_id = row.names (OrderByCluster),
  clust = clusterDF)  %>% arrange (clusterDF$Cluster)
#view(module_df)
#write.csv(module_df, file= "./DerivedData/1_IMvH2Kclusters_test1.csv", quote=F, row.names=FALSE)
```


```{r CODE CHUNK 9 DEG NUmbers}
plotMA (dds.ds, alpha = 0.01)
plotMA (dds.ds, alpha = 0.05)

#to see how many genes are < to 0.05
table (res$padj < 0.05) 
print (res)

#to see how many genes are < to 0.001
table (res$padj < 0.01) 
print (res)
```


```{r CODE CHUNK 10 VENN DIAGRAM SET UP}
#library(VennDiagram)
#dds.ds$groups
#resultsNames(dds.ds)
library(org.At.tair.db)
class(org.At.tair.db)
columns(org.At.tair.db)

dds$groups <- relevel (dds$groups, ref = "UM" ) #make sure groups are ok
dds.ds <- DESeq (dds) #Run DESeq
res <- results (dds.ds, alpha = 0.05)
#write.csv(res, file= "./DerivedData/1_DEG_ImvH_v1.csv", quote=F, row.names=TRUE)
pad <- 0.05
```




```{r UNK 11 }
#extract separate results
#IM vs UM
UMVsIM <- results (dds.ds, c('groups', 'IM', 'UM'))

UMVsIM$symbol = mapIds (org.At.tair.db, keys = row.names (UMVsIM) , keytype = "TAIR" , column = "SYMBOL" , multiVals = "first" )
UMVsIM$entrez = mapIds (org.At.tair.db, keys = row.names (UMVsIM) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

library(clusterProfiler)
IM_DF <- UMVsIM %>% 
  as.data.frame() %>%
  rownames_to_column (., var = "rowname") %>%
  as_tibble() %>% 
  na.omit()

IM_DEG_table <- IM_DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'IM_UP',
  log2FoldChange < 1 &   padj < pad ~ 'IM_DOWN',
  padj > pad ~ 'NO' ))

IM_DEG_table <- IM_DEG_table [IM_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes
# Substitute names so they are annotated nicely in the heatmap later
unique (IM_DEG_table$diffexpressed)

# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
IM_results_split <- split (IM_DEG_table,IM_DEG_table$diffexpressed)

IM_UP_DF <- IM_results_split$IM_UP [, c("rowname", "symbol", "entrez", "log2FoldChange", "padj" )] #%>% write.csv("./DerivedData/1_DEG_IMvUM_IMUP_pad05_LFC1_v1.csv") 

IM_DWN_DF <- IM_results_split$IM_DOWN [, c("rowname", "symbol", "entrez", "log2FoldChange", "padj" )] #%>% write.csv("./DerivedData/1_DEG_IMvUM_IMDWN_pad05_LFC1_v1.csv")

```





```{r}
library(clusterProfiler)
HVsIM <- results (dds.ds, c('groups', 'H', 'IM'))

HVsIM$symbol = mapIds (org.At.tair.db, keys = row.names (HVsIM) , keytype = "TAIR" , column = "SYMBOL" , multiVals = "first" )
HVsIM$entrez = mapIds (org.At.tair.db, keys = row.names (HVsIM) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

DF <- HVsIM %>% 
  as.data.frame() %>%
  rownames_to_column (., var = "rowname") %>%
  as_tibble() %>% 
  na.omit() 

DEG_table <- DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'UP',
  log2FoldChange < 1 &   padj < pad ~ 'DOWN',
  padj > pad ~ 'NO' ))

DEG_table <- DEG_table [DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heatmap later
unique (DEG_table$diffexpressed)

# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
DEG_table_split <- split (DEG_table, DEG_table$diffexpressed)


HvIM_UP_DF <- DEG_table_split$UP [, c("rowname", "entrez", "log2FoldChange", "padj", "symbol" )] #%>% write.csv("./DerivedData/1_DEG_HvIMUP_pad05_LFC1_v1.csv") 

HvIM_DWN_DF <- DEG_table_split$DOWN [, c("rowname", "entrez", "log2FoldChange", "padj", "symbol" )] #%>% write.csv("./DerivedData/1_DEG_HvIMDWN_pad05_LFC1_v1.csv") 


```

