---
title: "1_Diagnostics_DEG_Notebook"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
# ICM 2024MAY15 DESeq2 Script
# UM v IM v H

```{r CODE CHUNK 1 CLEAR}
# Clean environment
rm (list = ls (all.names = TRUE)) # will clear all objects including hidden objects
gc () # free up memory and report the memory usage
options (max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and keep scientific notation
```


```{r CHUNK 2 Packages}
# Remove hashtags to install any missing packages
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("escape")
#Install all
#BiocManager::install(c( "corrplot", "dendextend","readr","DESeq2", "ggrepel", "ggplot2", "pheatmap", "devtools", "ggforce","pheatmap", "gplots", "RColorBrewer", "ggdendro","enrichplot", "magrittr","dplyr","tibble", "tidyverse", "ComplexHeatmap", "escape")) 
#install one
#BiocManager::install(c("VennDetail"))

# Set the working directory to your project folder
setwd("~/Desktop/Lab/Working_Projects/R_trapseq_2023")
# Load necessary packages
suppressPackageStartupMessages({
  library(DESeq2)
  library(readr)
  library(tidyverse)
  library(enrichplot)
  #library(dplyr)
  #library(tibble)
  #library(magrittr)
  library(gplots)
  library(RColorBrewer)
  #library(corrplot)
#  library(ggdendro)
  library(dendextend)
  library(ggplot2)
  library(ggrepel)
  library(pheatmap)
  library(xlsx)
#  library(escape)
  library(clusterProfiler)
  library(org.At.tair.db)
})


# Read in raw count data from txt file 
featcount <- read_table ("./RawData/featcount.txt", col_names = TRUE, skip = 1)
read.count <- data.frame (featcount, row.names = featcount$Geneid)  # Set gene IDs as row names
read.count <- read.count [, -c(1:6)]  # Remove columns not related to gene counts
# Rename columns for consistency
orig_names <- names (read.count)  # Backup original names
colnames (read.count) <- c ("IT-107", "IT-108", "IT-109", "IT-110", "H-107", "H-108", "H-109", "H-110", "H-111", "UT-106", "UT-108", "UT-114", "IT-206", "IT-207", "IT-208", "IT-209", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UT-204", "UT-208", "UT-213", "UT-214", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215")
```



```{r CHUNK 6 Set Variables}
# Modifying for our purposes 
ImvHvUM <- read.count [ ,-c(1:4,10:16,22:25)]

#Variables
sample_info_UM <- data.frame(
  Sample = c ( "H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  Groups = c ( "H", "H", "H", "H", "H", "IM", "IM", "IM", "IM", "IM", "UM", "UM", "UM", "UM", "UM"),
  Condition = c ("Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Uninfected", "Uninfected", "Uninfected", "Uninfected", "Uninfected"),
  Replicate = c ("H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  row.names = "Sample") 

sample_info_UM$Groups <- as.factor (sample_info_UM$Groups)
all (rownames (sample_info_UM) %in% colnames (ImvHvUM)) 
#if "false" something is wrong
```


```{r Data Matrix}
# Create a DESeqDataSet object from the matrix of counts and column metadata  

data_set <- DESeqDataSetFromMatrix (countData = ImvHvUM, 
                               colData = sample_info_UM, 
                               design = ~ Groups)

# Prefilter
data_set <- data_set [rowSums (counts (data_set)) > 10, ]
# Set control group
data_set$Groups <- relevel (data_set$Groups, ref = "UM")

```


```{r Normalization}
# Perform variance stabilizing transformation (VST) for visualization and clustering
vsd <- vst (data_set)
colnames (vsd) <- sample_info_UM$Replicate 
norm.counts <- assay (data_set) #%>%
#   as.data.frame() %>% rownames_to_column (., var = "rowname")

#write.csv (norm.counts, file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_normalized.csv", quote = FALSE, row.names = TRUE)

#write.xlsx(as.data.frame(norm.counts), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_normalized.xlsx", sheetName = "normalized", col.names = TRUE, row.names = FALSE, append = FALSE)
```


```{r DESEQ2}
results_object <- DESeq (data_set)  # Perform DE analysis
res <- results (results_object)  # Extract Complete results
```


```{r Gene Expression}
d <- plotCounts(results_object, 
                 gene = "AT1G21890", 
                 intgroup = "Groups", 
                 returnData = TRUE)

# Create plot with jittered points and gene labels
ggplot (d, aes (x = Groups, y = count, color = Groups)) +
  geom_point (position = position_jitter (w = 0.1, h = 0)) +
  geom_text_repel (aes (label = rownames (d))) +
  theme_bw () +
  ggtitle ("AT1G21890 Expression") +
  theme (plot.title = element_text (hjust = 0.5))
#ggsave("./SumData/1_Diag_DEG/1_countData_AT1G21890.pdf")
```


```{r PCA}
# PCA principle component analysis, visualize the similarities and differences between *samples*
pc_data <- plotPCA (vsd, intgroup = c( "Replicate" , "Groups" ), returnData = TRUE) 
percentVar <- round (100 * attr (pc_data, "percentVar" ))

p <- ggplot (pc_data, aes(PC1, PC2, label = Replicate, colour = Groups)) +
  geom_point (aes (shape = Groups), size = 4) + scale_color_manual (values = c( "#FF093E", "#FF9900", "#861F41" )) +
   theme_classic()

p2 <- p + geom_text_repel (box.padding = 1, cex = 3, max.overlaps = 30, segment.linetype = 2) + labs (title = "PCA of VST Normalized Gene Counts" ) +
  xlab(paste0 ( "PC1: ", percentVar[1], "% variance" )) +
  ylab(paste0 ( "PC2: ", percentVar[2], "% variance" ))
p2
#ggsave("./SumData/1_Diag_DEG/1_PCA_Final_IMVUMVH_v2.pdf", width = 6, height = 6)
```


```{r SAMPLE TO SAMPLE COMPARISON}
library(brew)
# Calculate sample distances and create hierarchical clustering
sample_dist <- norm.counts [complete.cases (norm.counts), ] 
correlation_matrix <- cor (sample_dist, method = "spearman")
dist_matrix <- as.dist (1 - correlation_matrix)

# Hierarchical clustering
clustering_result <- hclust (dist_matrix, method = "complete")
dendrogram_object <- as.dendrogram (clustering_result) %>% color_branches (k = 3)
 
# Plot dendrogram
plot (dendrogram_object, type = "rectangle", ylab = "Height", main = "VST Read Counts - Distance: Spearman Correlation")
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_DistMat_clusters.pdf")

# Create heatmap of distance matrix using pheatmap package  
DistMatrix <- as.matrix (dist_matrix)
rownames (DistMatrix) <- paste (vsd$Replicate, sep = "-")
colnames (DistMatrix) <- paste (vsd$Replicate, sep = "-")
color_scheme <- colorRampPalette (rev (brewer.pal (9, "Blues")))(255)

pheatmap (DistMatrix, clustering_distance_rows = dist_matrix, clustering_distance_cols = dist_matrix, 
         color = color_scheme, main = "Sample Distance Matrix Heatmap")

#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_DistMatrix.pdf")
```


```{r}
set.seed(123)
significantly_different_genes = res %>%
   as.data.frame() %>%
   filter (padj < 0.05) %>%
  filter (abs (log2FoldChange) >= 1) #%>% write.csv("./DerivedData/1_DEG_HvIMvUM_padj05LCF1.csv") 

#Order genes by p.value and Extract Gene Names with the desired adjusted p-value cut-off
DGE.results.sorted <- significantly_different_genes [order (significantly_different_genes$padj), ]
DGEgenes <- rownames (subset (DGE.results.sorted, padj < 0.05))
hm.mat_DGEgenes <- norm.counts [DGEgenes, ]


pheatmap_differential_expression <- pheatmap (hm.mat_DGEgenes, show_rownames = FALSE, angle_col = c( "45" ), color = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu")))(100)#, 
            #cluster_rows = TRUE,
           # clustering_distance_rows = "correlation", 
          #  cluster_cols = TRUE,
          #  clustering_distance_cols = "correlation", 
           # clustering_method = "complete", 
            #scale = "row", cutree_cols = 2, 
            #cutree_rows = 2, 
          #  kmeans_k = 2
  )
#dev.copy2pdf(file="./SumData/1_Diag_DEG/1_hmap_IMvHvUM_official1.pdf")
```


```{r}
k <- pheatmap (hm.mat_DGEgenes, scale = "row", kmeans_k = 10)
clusterDF <- as.data.frame (factor (k$kmeans$cluster))
colnames (clusterDF) <- "Cluster"
clusterDF [1:10, , drop = FALSE]

OrderByCluster <- hm.mat_DGEgenes [order (clusterDF$Cluster), ]
pheatmap (OrderByCluster, scale = "row", annotation_row = clusterDF, show_rownames = FALSE,
    cluster_rows = FALSE)
```


```{r}
library (NbClust)
rowScaledMat <- t(scale (t(OrderByCluster)))
clusterNum <- NbClust (rowScaledMat, distance = "euclidean", min.nc = 2, max.nc = 12,
    method = "kmeans", index = "silhouette")
clusterNum$Best.nc
clusterNum$Best.partition[1:10]
orderedCluster <- sort(clusterNum$Best.partition)
OrderByCluster <- OrderByCluster [match(names(orderedCluster), rownames(OrderByCluster)), ]
pheatmap(OrderByCluster, scale = "row", annotation_row = clusterDF, show_rownames = FALSE,
    cluster_rows = FALSE)
```


```{r H v UM DEGS}
pad <- 0.05
UMvsH <- results (results_object, c( "Groups", "H", "UM" ))

# Map TAIR IDs to ENTREZ IDs
UMvsH$entrez <- mapIds (org.At.tair.db, keys = row.names (UMvsH), keytype = "TAIR", column = "ENTREZID", multiVals = "first") 
UMvsH$symbol <- mapIds (org.At.tair.db, keys = row.names (UMvsH), keytype = "TAIR", column = "SYMBOL", multiVals = "first")

H_DF <- UMvsH %>% 
  as.data.frame() %>% rownames_to_column (., var = "rowname") %>% as_tibble() %>% na.omit()
#write.csv (H_DF, file = "./DerivedData/1_Diag_DEG/1_DEG_HvUM_NoFilters.csv", quote = FALSE, row.names = TRUE)
 
H_DEG_table <- H_DF %>% 
  mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'H_UP',
  log2FoldChange < -1 &   padj < pad ~ 'H_DOWN',
  padj > pad ~ 'NO' ))  %>%  na.omit()

H_DEG_table <- H_DEG_table [H_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
unique (H_DEG_table$diffexpressed)
#write.csv (H_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_HvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)

# Split the data frame into sub-data frames: up/down regulated genes
H_results_split <- split (H_DEG_table, H_DEG_table$diffexpressed)
HDOWN <- c (H_results_split$H_DOWN)
HDOWN <- as.data.frame (HDOWN, row.names = HDOWN$entrez)
HUP <- c (H_results_split$H_UP)
HUP <- as.data.frame (HUP, row.names = HUP$entrez)

#write.xlsx(as.data.frame(H_DF), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_nofilter.xlsx", sheetName = "HvUM", col.names = TRUE, row.names = FALSE, append = FALSE)
```


```{r IM V UM DEG}
UMVsIM <- results (results_object, c('Groups', 'IM', 'UM'))

# Map TAIR IDs to ENTREZ IDs
UMVsIM$entrez <- mapIds(org.At.tair.db, keys = row.names(UMVsIM), keytype = "TAIR", column = "ENTREZID", multiVals = "first")
UMVsIM$symbol <- mapIds (org.At.tair.db, keys = row.names (UMVsIM), keytype = "TAIR", column = "SYMBOL", multiVals = "first")

IM_DF <- UMVsIM %>% as.data.frame() %>% rownames_to_column (., var = "rowname") %>% as_tibble() %>%  na.omit()

#write.csv(IM_DF, file = "./DerivedData/1_Diag_DEG/1_DEG_IMvUM_NoFilters.csv", quote = FALSE, row.names = TRUE)
 
IM_DEG_table <- IM_DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'IM_UP',
  log2FoldChange < -1 &   padj < pad ~ 'IM_DOWN',
  padj > pad ~ 'NO' )) %>%  na.omit()

IM_DEG_table <- IM_DEG_table [IM_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
unique (IM_DEG_table$diffexpressed)

#write.csv(IM_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_IMvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)
 
# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
IM_results_split <- split (IM_DEG_table, IM_DEG_table$diffexpressed)
IMDOWN <- c(IM_results_split$IM_DOWN)
IMDOWN <- as.data.frame (IMDOWN, row.names = IMDOWN$entrez)
IMUP <- c (IM_results_split$IM_UP)
IMUP <- as.data.frame (IMUP, row.names = IMUP$entrez)

#write.csv (IMUP, file = "./DerivedData/1_Diag_DEG/1_DEG_IMUP_LFC1p05.csv", quote = FALSE, row.names = TRUE)

#write.xlsx(as.data.frame(IM_DF), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_nofilter.xlsx", sheetName = "IMvUM", col.names = TRUE, row.names = FALSE, append = TRUE)
```


```{r H Vs IM}
#length (H_DF$rowname) <- length (HvIM.UM$rowname)
ven <- VennDetail::venndetail (list (HvsUM = H_DEG_table$rowname, IMvsUM = IM_DEG_table$rowname))
plot(ven, type = "venn", order = TRUE, textsize = 3)
plot(ven, type = "venn", col = c("orchid", "#d95f02"), sep = "_",
mycol = c("orchid", "#d95f02"), cat.cex = 1.5, alpha = 0.5, cex = 2,
cat.fontface = "bold", margin = 0.05, text.scale = c(1.5, 1.5), filename = NULL, piecolor = NULL,
revcolor = "blue", any = NULL, show.number = TRUE,
show.x = TRUE, log = FALSE, base = NULL, percentage = FALSE,
sets.x.label = "Set Size", mainbar.y.label = "Intersection Size",
nintersects = 40, abbr = TRUE, abbr.method = "both.sides",
minlength = 3)
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_Upset_IMvHvUM.pdf")


HUM_venlist<- as.data.frame(VennDetail::getSet(ven, "HvsUM"))
IMUM_venlist<- as.data.frame(VennDetail::getSet(ven, "IMvsUM"))
#VennDetail::make.subset(ven, "HvsUM")
VennDetail::result(ven)
VennDetail::vennpie(ven)
```

```{r}
#Order genes by p.value and Extract Gene Names with the desired adjusted p-value cut-off
hm.mat_DGEgenes <- norm.counts [HUM_venlist$Detail, ]


pheatmap_differential_expression <- pheatmap (hm.mat_DGEgenes, show_rownames = FALSE, angle_col = c( "45" ), color = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu")))(100), 
            #cluster_rows = TRUE,
           # clustering_distance_rows = "correlation", 
            cluster_cols = TRUE,
           # clustering_distance_cols = "correlation", 
           # clustering_method = "complete", 
            scale = "row", cutree_cols = 2, 
            #cutree_rows = 2, 
          #  kmeans_k = 2
  )

mat_DGEgenes <- norm.counts [IMUM_venlist$Detail, ]


pheatmap_differential_expression <- pheatmap (mat_DGEgenes, show_rownames = FALSE, angle_col = c( "45" ), color = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu")))(100), 
            cluster_rows = TRUE,
            clustering_distance_rows = "correlation", 
            cluster_cols = TRUE,
            clustering_distance_cols = "correlation", 
            clustering_method = "complete", 
            scale = "row", cutree_cols = 2, 
            #cutree_rows = 2, 
          #  kmeans_k = 2
  )
```


```{r}
# Cluster analysis
set.seed(123)
names(k$kmeans)
str(k)

clusterDF <- as.data.frame(factor(k$kmeans$cluster))
colnames(clusterDF) <- "Cluster"
clusterDF[1:10, , drop = FALSE]
OrderByCluster <- clusterDF %>% arrange(Cluster)

```

```{r}
module_df <- data.frame(
  gene_id = row.names (OrderByCluster),
  clust = clusterDF)  %>% arrange (clusterDF$Cluster)
#view(module_df)
#write.csv(module_df, file= "./DerivedData/1_IMvH2Kclusters_test1.csv", quote=F, row.names=FALSE)
```


```{r CODE CHUNK 9 DEG NUmbers}
plotMA (results_object, alpha = 0.01)
plotMA (results_object, alpha = 0.05)

#to see how many genes are < to 0.05
table (results_object$padj < 0.05) 
print (results_object)

#to see how many genes are < to 0.001
table (results_object$padj < 0.01) 
print (results_object)
```


```{r}
#length (H_DF$rowname) <- length (HvIM.UM$rowname)
ven <- VennDetail::venndetail (list (HvsUM = H_DEG_table$rowname, IMvsUM = IM_DEG_table$rowname, HvsIM = HIMum_DEG_table$rowname))
plot(ven, type = "venn", order = TRUE, textsize = 3)
plot(ven, type = "venn", col = c("#1b9e77", "#d95f02", "orchid3"), sep = "_",
mycol = c("#1b9e77", "#d95f02", "orchid3"), cat.cex = 1.5, alpha = 0.5, cex = 2,
cat.fontface = "bold", margin = 0.05, text.scale = c(1.5, 1.5, 1.5), filename = NULL, piecolor = NULL,
revcolor = "blue", any = NULL, show.number = TRUE,
show.x = TRUE, log = FALSE, base = NULL, percentage = FALSE,
sets.x.label = "Set Size", mainbar.y.label = "Intersection Size",
nintersects = 40, abbr = TRUE, abbr.method = "both.sides",
minlength = 3)
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_Upset_IMvHvUM.pdf")

```


```{r}
VennDetail::detail(ven)
VennDetail::dplot(ven)

HIM_venlist<- as.data.frame(VennDetail::getSet(ven, "HvsIM"))
VennDetail::make.subset(ven, "HvsIM")
VennDetail::result(ven)
VennDetail::vennpie(ven)
```

```{r}
HIM_detail<- as.data.frame(HIM_venlist, row.names = HIM_venlist$Detail)

HIM_detail$ENTREZ = mapIds (org.At.tair.db, keys = row.names (HIM_detail) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

HIM_detail$symbol <- mapIds (org.At.tair.db, keys = row.names (HIM_detail), keytype = "TAIR", column = "SYMBOL", multiVals = "first")

#write.csv(HIM_detail, file= "./DerivedData/1_Diag_DEG/1_HIM_167uniq.csv", quote=F, row.names=FALSE)


HIM_LFC_uniq <- HIMum_DEG_table %>%
  subset (HIMum_DEG_table$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 

HIM_LFC_uniq2 <- IM_DF %>%
  subset (IM_DF$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 

HIM_LFC_uniq3 <- H_DF %>%
  subset (H_DF$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 


#write.csv(HIM_uniq_genes, file= "./DerivedData/1_Diag_DEG/1_HIM_uniq.csv", quote=F, row.names=FALSE)
```


```{r}
results_object1 <- DESeq(data_set1, betaPrior = FALSE)

res5 <- lfcShrink(results_object, contrast = c('Groups','IM','UM'), res=UMVsIM1, type = 'normal')
res6 <- lfcShrink(results_object, contrast = c('Groups','H','UM'), res=UMVsH1, type = 'normal')
res7 <- lfcShrink(results_object, contrast = c('Groups','H','IM'), res=HvIM.UM, type = 'normal')
```


```{r}
library(EnhancedVolcano)
EnhancedVolcano (HvIM.UM,
    lab = HvIM.UM$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010', 'AT1G02205', 'AT1G03920', 'AT1G06100', 'AT1G11475', 'AT1G12750', 'AT1G13140', 'AT1G14760', 'AT1G15960', 'AT1G17260', 'AT1G19840', 'AT1G20160', 'AT1G21890', 'AT1G23380', 'AT1G24030', 'AT1G24070', 'AT1G27370', 'AT1G30650', 'AT1G32310', 'AT1G36180', 'AT1G48175', 'AT1G48360', 'AT1G51340', 'AT1G58230', 'AT1G58360', 'AT1G60260', 'AT1G60270', 'AT1G61590', 'AT1G62310', 'AT1G62420', 'AT1G62790', 'AT1G63100', 'AT1G63180', 'AT1G65450', 'AT1G66080', 'AT1G66730', 'AT1G67120', 'AT1G67140', 'AT1G70680', 'AT1G71050', 'AT1G71890', 'AT1G71960', 'AT1G77320', 'AT1G77680', 'AT1G78080', 'AT1G79780', 'AT1G80760', 'AT2G01730', 'AT2G02850', 'AT2G03760', 'AT2G11810', 'AT2G13540', 'AT2G20020', 'AT2G21140', 'AT2G22970', 'AT2G24700', 'AT2G27510', 'AT2G28930', 'AT2G30080', 'AT2G30590', 'AT2G31250', 'AT2G31900', 'AT2G31970', 'AT2G33850', 'AT2G34850', 'AT2G35160', 'AT2G35340', 'AT2G35630', 'AT2G35950', 'AT2G36810', 'AT2G37170', 'AT2G37460', 'AT2G37580', 'AT2G40100', 'AT2G41940', 'AT2G44860', 'AT2G47260', 'AT2G47730', 'AT3G01140', 'AT3G02030', 'AT3G03030', 'AT3G05040', 'AT3G06260', 'AT3G06370', 'AT3G09390', 'AT3G12810', 'AT3G12890', 'AT3G13225', 'AT3G14000', 'AT3G14360', 'AT3G14640', 'AT3G18490', 'AT3G19450', 'AT3G23290', 'AT3G23325', 'AT3G23430', 'AT3G30530', 'AT3G42640', 'AT3G44260', 'AT3G44900', 'AT3G45010', 'AT3G45420', 'AT3G46010', 'AT3G47360', 'AT3G47380', 'AT3G48190', 'AT3G48480', 'AT3G49840', 'AT3G49920', 'AT3G51060', 'AT3G54140', 'AT3G59100', 'AT3G60720', 'AT4G00490', 'AT4G00760', 'AT4G00930', 'AT4G01190', 'AT4G04760', 'AT4G08150', 'AT4G13235', 'AT4G14465', 'AT4G15320', 'AT4G20060', 'AT4G21410', 'AT4G22970', 'AT4G23290', 'AT4G27010', 'AT4G31160', 'AT4G33070', 'AT4G33560', 'AT4G34050', 'AT4G35420', 'AT4G36270', 'AT4G36710', 'AT4G36930', 'AT4G40010', 'AT5G02810', 'AT5G03720', 'AT5G08230', 'AT5G11950', 'AT5G13840', 'AT5G19650', 'AT5G28490', 'AT5G38140', 'AT5G39190', 'AT5G40330', 'AT5G43730', 'AT5G44180', 'AT5G44400', 'AT5G44572', 'AT5G44580', 'AT5G44582', 'AT5G48930', 'AT5G49620', 'AT5G49630', 'AT5G50460', 'AT5G51451', 'AT5G53830', 'AT5G53920', 'AT5G58160', 'AT5G58500', 'AT5G61140', 'AT5G61740', 'AT5G63090', 'AT5G63850', 'AT5G64800', 'AT5G66610'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'IMvUM',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)


EnhancedVolcano(IM_DF,
    lab = IM_DF$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010', 'AT1G02205', 'AT1G03920', 'AT1G06100', 'AT1G11475', 'AT1G12750', 'AT1G13140', 'AT1G14760', 'AT1G15960', 'AT1G17260', 'AT1G19840', 'AT1G20160', 'AT1G21890', 'AT1G23380', 'AT1G24030', 'AT1G24070', 'AT1G27370', 'AT1G30650', 'AT1G32310', 'AT1G36180', 'AT1G48175', 'AT1G48360', 'AT1G51340', 'AT1G58230', 'AT1G58360', 'AT1G60260', 'AT1G60270', 'AT1G61590', 'AT1G62310', 'AT1G62420', 'AT1G62790', 'AT1G63100', 'AT1G63180', 'AT1G65450', 'AT1G66080', 'AT1G66730', 'AT1G67120', 'AT1G67140', 'AT1G70680', 'AT1G71050', 'AT1G71890', 'AT1G71960', 'AT1G77320', 'AT1G77680', 'AT1G78080', 'AT1G79780', 'AT1G80760', 'AT2G01730', 'AT2G02850', 'AT2G03760', 'AT2G11810', 'AT2G13540', 'AT2G20020', 'AT2G21140', 'AT2G22970', 'AT2G24700', 'AT2G27510', 'AT2G28930', 'AT2G30080', 'AT2G30590', 'AT2G31250', 'AT2G31900', 'AT2G31970', 'AT2G33850', 'AT2G34850', 'AT2G35160', 'AT2G35340', 'AT2G35630', 'AT2G35950', 'AT2G36810', 'AT2G37170', 'AT2G37460', 'AT2G37580', 'AT2G40100', 'AT2G41940', 'AT2G44860', 'AT2G47260', 'AT2G47730', 'AT3G01140', 'AT3G02030', 'AT3G03030', 'AT3G05040', 'AT3G06260', 'AT3G06370', 'AT3G09390', 'AT3G12810', 'AT3G12890', 'AT3G13225', 'AT3G14000', 'AT3G14360', 'AT3G14640', 'AT3G18490', 'AT3G19450', 'AT3G23290', 'AT3G23325', 'AT3G23430', 'AT3G30530', 'AT3G42640', 'AT3G44260', 'AT3G44900', 'AT3G45010', 'AT3G45420', 'AT3G46010', 'AT3G47360', 'AT3G47380', 'AT3G48190', 'AT3G48480', 'AT3G49840', 'AT3G49920', 'AT3G51060', 'AT3G54140', 'AT3G59100', 'AT3G60720', 'AT4G00490', 'AT4G00760', 'AT4G00930', 'AT4G01190', 'AT4G04760', 'AT4G08150', 'AT4G13235', 'AT4G14465', 'AT4G15320', 'AT4G20060', 'AT4G21410', 'AT4G22970', 'AT4G23290', 'AT4G27010', 'AT4G31160', 'AT4G33070', 'AT4G33560', 'AT4G34050', 'AT4G35420', 'AT4G36270', 'AT4G36710', 'AT4G36930', 'AT4G40010', 'AT5G02810', 'AT5G03720', 'AT5G08230', 'AT5G11950', 'AT5G13840', 'AT5G19650', 'AT5G28490', 'AT5G38140', 'AT5G39190', 'AT5G40330', 'AT5G43730', 'AT5G44180', 'AT5G44400', 'AT5G44572', 'AT5G44580', 'AT5G44582', 'AT5G48930', 'AT5G49620', 'AT5G49630', 'AT5G50460', 'AT5G51451', 'AT5G53830', 'AT5G53920', 'AT5G58160', 'AT5G58500', 'AT5G61140', 'AT5G61740', 'AT5G63090', 'AT5G63850', 'AT5G64800', 'AT5G66610'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'IMvUM',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)

EnhancedVolcano(H_DF,
    lab = H_DF$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010', 'AT1G02205', 'AT1G03920', 'AT1G06100', 'AT1G11475', 'AT1G12750', 'AT1G13140', 'AT1G14760', 'AT1G15960', 'AT1G17260', 'AT1G19840', 'AT1G20160', 'AT1G21890', 'AT1G23380', 'AT1G24030', 'AT1G24070', 'AT1G27370', 'AT1G30650', 'AT1G32310', 'AT1G36180', 'AT1G48175', 'AT1G48360', 'AT1G51340', 'AT1G58230', 'AT1G58360', 'AT1G60260', 'AT1G60270', 'AT1G61590', 'AT1G62310', 'AT1G62420', 'AT1G62790', 'AT1G63100', 'AT1G63180', 'AT1G65450', 'AT1G66080', 'AT1G66730', 'AT1G67120', 'AT1G67140', 'AT1G70680', 'AT1G71050', 'AT1G71890', 'AT1G71960', 'AT1G77320', 'AT1G77680', 'AT1G78080', 'AT1G79780', 'AT1G80760', 'AT2G01730', 'AT2G02850', 'AT2G03760', 'AT2G11810', 'AT2G13540', 'AT2G20020', 'AT2G21140', 'AT2G22970', 'AT2G24700', 'AT2G27510', 'AT2G28930', 'AT2G30080', 'AT2G30590', 'AT2G31250', 'AT2G31900', 'AT2G31970', 'AT2G33850', 'AT2G34850', 'AT2G35160', 'AT2G35340', 'AT2G35630', 'AT2G35950', 'AT2G36810', 'AT2G37170', 'AT2G37460', 'AT2G37580', 'AT2G40100', 'AT2G41940', 'AT2G44860', 'AT2G47260', 'AT2G47730', 'AT3G01140', 'AT3G02030', 'AT3G03030', 'AT3G05040', 'AT3G06260', 'AT3G06370', 'AT3G09390', 'AT3G12810', 'AT3G12890', 'AT3G13225', 'AT3G14000', 'AT3G14360', 'AT3G14640', 'AT3G18490', 'AT3G19450', 'AT3G23290', 'AT3G23325', 'AT3G23430', 'AT3G30530', 'AT3G42640', 'AT3G44260', 'AT3G44900', 'AT3G45010', 'AT3G45420', 'AT3G46010', 'AT3G47360', 'AT3G47380', 'AT3G48190', 'AT3G48480', 'AT3G49840', 'AT3G49920', 'AT3G51060', 'AT3G54140', 'AT3G59100', 'AT3G60720', 'AT4G00490', 'AT4G00760', 'AT4G00930', 'AT4G01190', 'AT4G04760', 'AT4G08150', 'AT4G13235', 'AT4G14465', 'AT4G15320', 'AT4G20060', 'AT4G21410', 'AT4G22970', 'AT4G23290', 'AT4G27010', 'AT4G31160', 'AT4G33070', 'AT4G33560', 'AT4G34050', 'AT4G35420', 'AT4G36270', 'AT4G36710', 'AT4G36930', 'AT4G40010', 'AT5G02810', 'AT5G03720', 'AT5G08230', 'AT5G11950', 'AT5G13840', 'AT5G19650', 'AT5G28490', 'AT5G38140', 'AT5G39190', 'AT5G40330', 'AT5G43730', 'AT5G44180', 'AT5G44400', 'AT5G44572', 'AT5G44580', 'AT5G44582', 'AT5G48930', 'AT5G49620', 'AT5G49630', 'AT5G50460', 'AT5G51451', 'AT5G53830', 'AT5G53920', 'AT5G58160', 'AT5G58500', 'AT5G61140', 'AT5G61740', 'AT5G63090', 'AT5G63850', 'AT5G64800', 'AT5G66610'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'UMvsH',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)
```


```{r}
atguniq<- c('AT1G02010', 'AT1G02205', 'AT1G03920', 'AT1G06100', 'AT1G11475', 'AT1G12750', 'AT1G13140', 'AT1G14760', 'AT1G15960', 'AT1G17260', 'AT1G19840', 'AT1G20160', 'AT1G21890', 'AT1G23380', 'AT1G24030', 'AT1G24070', 'AT1G27370', 'AT1G30650', 'AT1G32310', 'AT1G36180', 'AT1G48175', 'AT1G48360', 'AT1G51340', 'AT1G58230', 'AT1G58360', 'AT1G60260', 'AT1G60270', 'AT1G61590', 'AT1G62310', 'AT1G62420', 'AT1G62790', 'AT1G63100', 'AT1G63180', 'AT1G65450', 'AT1G66080', 'AT1G66730', 'AT1G67120', 'AT1G67140', 'AT1G70680', 'AT1G71050', 'AT1G71890', 'AT1G71960', 'AT1G77320', 'AT1G77680', 'AT1G78080', 'AT1G79780', 'AT1G80760', 'AT2G01730', 'AT2G02850', 'AT2G03760', 'AT2G11810', 'AT2G13540', 'AT2G20020', 'AT2G21140', 'AT2G22970', 'AT2G24700', 'AT2G27510', 'AT2G28930', 'AT2G30080', 'AT2G30590', 'AT2G31250', 'AT2G31900', 'AT2G31970', 'AT2G33850', 'AT2G34850', 'AT2G35160', 'AT2G35340', 'AT2G35630', 'AT2G35950', 'AT2G36810', 'AT2G37170', 'AT2G37460', 'AT2G37580', 'AT2G40100', 'AT2G41940', 'AT2G44860', 'AT2G47260', 'AT2G47730', 'AT3G01140', 'AT3G02030', 'AT3G03030', 'AT3G05040', 'AT3G06260', 'AT3G06370', 'AT3G09390', 'AT3G12810', 'AT3G12890', 'AT3G13225', 'AT3G14000', 'AT3G14360', 'AT3G14640', 'AT3G18490', 'AT3G19450', 'AT3G23290', 'AT3G23325', 'AT3G23430', 'AT3G30530', 'AT3G42640', 'AT3G44260', 'AT3G44900', 'AT3G45010', 'AT3G45420', 'AT3G46010', 'AT3G47360', 'AT3G47380', 'AT3G48190', 'AT3G48480', 'AT3G49840', 'AT3G49920', 'AT3G51060', 'AT3G54140', 'AT3G59100', 'AT3G60720', 'AT4G00490', 'AT4G00760', 'AT4G00930', 'AT4G01190', 'AT4G04760', 'AT4G08150', 'AT4G13235', 'AT4G14465', 'AT4G15320', 'AT4G20060', 'AT4G21410', 'AT4G22970', 'AT4G23290', 'AT4G27010', 'AT4G31160', 'AT4G33070', 'AT4G33560', 'AT4G34050', 'AT4G35420', 'AT4G36270', 'AT4G36710', 'AT4G36930', 'AT4G40010', 'AT5G02810', 'AT5G03720', 'AT5G08230', 'AT5G11950', 'AT5G13840', 'AT5G19650', 'AT5G28490', 'AT5G38140', 'AT5G39190', 'AT5G40330', 'AT5G43730', 'AT5G44180', 'AT5G44400', 'AT5G44572', 'AT5G44580', 'AT5G44582', 'AT5G48930', 'AT5G49620', 'AT5G49630', 'AT5G50460', 'AT5G51451', 'AT5G53830', 'AT5G53920', 'AT5G58160', 'AT5G58500', 'AT5G61140', 'AT5G61740', 'AT5G63090', 'AT5G63850', 'AT5G64800', 'AT5G66610')

library(ggplot2)
H_DF$log2FoldChange<- as.factor(H_DF$log2FoldChange)
IM_DF$log2FoldChange <- as.factor(IM_DF$log2FoldChange)
atguniq <- as.factor(atguniq)
# Basic scatter plot

#if(require("devtools") && require("BiocManager")){
#  options(repos = BiocManager::repositories() )
#  devtools::install_github("cparsania/parcutils")
#} else{
#  install.packages(c("devtools","BiocManager"))
#  options(repos = BiocManager::repositories() )
#  devtools::install_github("cparsania/parcutils")
#}
```

```{r}
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("vidger")
```

```{r}
library(vidger)
# DESeq2 example
hl <- c(atguniq)

data("results_object")
vsFourWay(
     x = "H", y = "IM",
     control = "UM", data = results_object,
     d.factor = "Groups", type = "deseq", padj = 0.05,
     x.lim = NULL, y.lim = NULL, lfc = 1, title = TRUE, grid = TRUE,
     data.return = FALSE, highlight = hl,  data.return = FALSE, xaxis.text.size = 10,
yaxis.text.size = 10, xaxis.title.size = 10, yaxis.title.size = 10,
main.title.size = 15, legend.text.size = 9
)
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_LFC_IMvHvUM.pdf")
```

```{r}
data("results_object")
vsBoxPlot(results_object, d.factor = "Groups", type = c("deseq"),
title = TRUE, legend = TRUE, grid = TRUE, aes = c("violin"), fill.color = NULL,
data.return = FALSE, xaxis.text.size = 10, yaxis.text.size = 10,
xaxis.title.size = 12, yaxis.title.size = 12, main.title.size = 15,
legend.text.size = 10, legend.title.size = 12)

vsDEGMatrix(results_object, padj = 0.05, d.factor = "Groups", type = c(
"deseq"), title = TRUE, legend = TRUE, grid = TRUE,
data.return = FALSE, grey.scale = FALSE, xaxis.text.size = 10,
yaxis.text.size = 10, main.title.size = 15, legend.text.size = 10,
legend.title.size = 12)

vsMAMatrix(results_object, d.factor = "Groups", type = c("deseq"),
padj = 0.05, y.lim = NULL, lfc = NULL, title = TRUE, legend = TRUE,
grid = TRUE, counts = TRUE, data.return = FALSE, xaxis.text.size = 9,
yaxis.text.size = 9, xaxis.title.size = 10, yaxis.title.size = 10,
main.title.size = 15, legend.text.size = 9, facet.title.size = 10)

vsScatterMatrix(results_object, d.factor = "Groups", type = c("deseq"), comp = NULL, title = TRUE, grid = TRUE, man.title = NULL,
data.return = FALSE, xaxis.text.size = 9, yaxis.text.size = 9,
xaxis.title.size = 10, yaxis.title.size = 10, main.title.size = 15,
facet.title.size = 10)

vsVolcanoMatrix(results_object, d.factor = "Groups", type = c("deseq"), padj = 0.05, x.lim = NULL, lfc = NULL, title = TRUE,
legend = TRUE, grid = TRUE, counts = TRUE, data.return = FALSE,
xaxis.text.size = 9, yaxis.text.size = 9, xaxis.title.size = 10,
yaxis.title.size = 10, main.title.size = 15, legend.text.size = 9,
facet.title.size = 10)
```



```{r}

him_uniq<- read_csv("./DerivedData/1_Diag_DEG/1_HIM_uniq.csv")
him_uniq_table <- him_uniq %>% 
  mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'H_UP',
  log2FoldChange < -1 &   padj < pad ~ 'H_DOWN',
  padj > pad ~ 'NO' ))  %>%  na.omit()

H_DEG_table <- him_uniq_table [him_uniq_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
unique (H_DEG_table$diffexpressed)
#write.csv (H_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_HvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)

# Split the data frame into sub-data frames: up/down regulated genes
H_results_split <- split (H_DEG_table, H_DEG_table$diffexpressed)
HDOWN <- c (H_results_split$H_DOWN)
HDOWN <- as.data.frame (HDOWN, row.names = HDOWN$entrez)
HUP <- c (H_results_split$H_UP)
HUP <- as.data.frame (HUP, row.names = HUP$entrez)
```





