---
title: "2_GSEA_Analysis"
output: html_notebook
---
```{r}
### INSTALLING PACKAGES ###
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")
#BiocManager::install(c("readr", "tidyverse", "org.At.tair.db", "clusterProfiler", "ggplot2", "enrichplot", "ggupset"))

# Clean environment
rm (list = ls (all.names = TRUE)) # will clear all objects including hidden objects
gc() # free up memory and report the memory usage
options (max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and scientific notation
```


```{r}
#Set Working Directory
setwd("~/Desktop/Lab/Working_Projects/R_trapseq_2023")

#Load Libraries
suppressPackageStartupMessages ({
  library (readr)
  library (tidyverse)
  library ("org.At.tair.db")
  library (clusterProfiler)
  library (org.At.tair.db)
  #class (org.At.tair.db)
  #columns (org.At.tair.db)
  library (ggplot2)
  library (enrichplot)
  library (ggupset)
  library (ggrepel)
  library ("fgsea")
  library (DOSE)
  library (pathview)
})
set.seed (123456)
#Set Pvalue Cutoff 
pad <- 0.05
```


```{r}
IMvUM <- read_csv ("./DerivedData/1_DESeq_Results/1_DES_Results_IMvUM.csv", col_names = TRUE) 
IM_DF <- as.data.frame (IMvUM, rownames = IMvUM$rowname)

HvUM <- read_csv ("./DerivedData/1_DESeq_Results/1_DES_Results_HvUM.csv", col_names = TRUE)
HvUM_DF <- as.data.frame (HvUM, rownames = HvUM$rowname)

HvIM.UM <- read_csv ("./DerivedData/1_DESeq_Results/1_DES_Results_H_HvIMvum.csv", col_names = TRUE)
HIMum_DF <- as.data.frame (HvIM.UM, rownames = HvIM.UM$rowname)
```


```{r Frame setup}
set.seed(123)

################################### IM v UM
## Remove NA
IM_DF_entrez <- dplyr::filter (IM_DF, entrez != "NA")
## Remove dups
IM_DF_entrez <- IM_DF_entrez [which (duplicated (IM_DF_entrez$entrez) == F), ]
## Extract foldchanges
foldchanges <- IM_DF_entrez$log2FoldChange
## Name each fold change with the corresponding Entrez ID
names (foldchanges) <- IM_DF_entrez$entrez
## Sort fold changes in decreasing order
foldchanges1 <- sort (foldchanges, decreasing = TRUE)


################################### H v UM
HvUM_DF_entrez <- dplyr::filter (HvUM_DF, entrez != "NA")
## Remove dups
HvUM_DF_entrez <- HvUM_DF_entrez [which (duplicated (HvUM_DF_entrez$entrez) == F), ]
## Extract foldchanges
foldchanges <- HvUM_DF_entrez$log2FoldChange
## Name each fold change with the corresponding Entrez ID
names (foldchanges) <- HvUM_DF_entrez$entrez
## Sort fold changes in decreasing order
foldchanges2 <- sort (foldchanges, decreasing = TRUE)


################################### H v IM
HIMum_DF_entrez <- dplyr::filter (HIMum_DF, entrez != "NA")
## Remove dups
HIMum_DF_entrez <- HIMum_DF_entrez [which (duplicated (HIMum_DF$entrez) == F), ]
## Extract foldchanges
foldchanges <- HIMum_DF_entrez$log2FoldChange
## Name each fold change with the corresponding Entrez ID
names (foldchanges) <- HIMum_DF_entrez$entrez
## Sort fold changes in decreasing order
foldchanges3 <- sort (foldchanges, decreasing = TRUE)
```


```{r GSEA KEGG}
## GSEA using gene sets from KEGG pathways
gseaKEGG1 <- gseKEGG (geneList = foldchanges1,
                    organism = "ath",
                    keyType = "ncbi-geneid",
                    minGSSize = 20, # minimum gene set size (# genes in set) - change to test more sets or recover sets with fewer # genes
                    pvalueCutoff = 0.05, #cutoff value
                    verbose = FALSE)

## GSEA using gene sets from KEGG pathways
gseaKEGG2 <- gseKEGG (geneList = foldchanges2,
                    organism = "ath",
                    keyType = "ncbi-geneid",
                    minGSSize = 20, # minimum gene set size (# genes in set) - change to test more sets or recover sets with fewer # genes
                    pvalueCutoff = 0.05, #cutoff value
                    verbose = FALSE)

## GSEA using gene sets from KEGG pathways
gseaKEGG3 <- gseKEGG (geneList = foldchanges3,
                    organism = "ath",
                    keyType = "ncbi-geneid",
                    minGSSize = 20, # minimum gene set size (# genes in set) - change to test more sets or recover sets with fewer # genes
                    pvalueCutoff = 0.05, #cutoff value
                    verbose = FALSE)
```


```{r Extract KEGG RESULTS}
## Extract the GSEA results
gseaKEGG1_results <- gseaKEGG1@result

gseaKEGG2_results <- gseaKEGG2@result

gseaKEGG3_results <- gseaKEGG3@result
```


```{r IM}
## GSEA using gene sets from GO pathways
gsea_go1 <- gseGO (geneList = foldchanges1,
                  OrgDb = org.At.tair.db,
                  ont = "ALL",
                  keyType ="ENTREZID",
                  seed = TRUE)


```

```{r}
## Output images for all significant KEGG pathways
get_kegg_plots <- function(x) {
   pathview (gene.data = foldchanges, pathway.id = gseaKEGG_results$ID[x], species = "ath", 
       limit = list(gene = 2, cpd = 1))
}
purrr::map(1:length(gseaKEGG_results$ID), get_kegg_plots)
```

```{r}
#enrichplot::gseaplot2(gseaKEGG, geneSetID = c(1:2))
#enrichplot::gseaplot2(gsea_go, geneSetID = c(1,2))

#enrichplot::upsetplot(gsea_go)
#enrichplot::upsetplot(gseaKEGG)

gsea_go1_2 <- filter (gsea_go1, NES > 1.95 | NES < -2)
gseaKEGG1_2 <- filter (gseaKEGG1, NES > 1.95 | NES < -2)
dim (gsea_go1_2)
dim (gseaKEGG1_2)

#replot upset plot
enrichplot::upsetplot (gsea_go1_2, n = 10)
#enrichplot::upsetplot(gseaKEGG2, n=10)

#plot using a barplot
ggplot (gsea_go1_2, showCategory = 10, aes (NES, fct_reorder (Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline (xintercept = 0, linetype = "dashed", color = "blue", size = 1) + 
  scale_fill_gradientn (colours = c("#b3eebe","#46bac2","#371ea3"), guide = guide_colorbar (reverse = TRUE)) + 
  scale_x_continuous (expand = c(0, 0)) + 
  theme_bw() +
#theme(text=element_text(size=8))+
  xlab("Normalized Enrichment Score") +
  ylab(NULL) +
ggtitle("GSEA with GO")

ggplot (gseaKEGG1_2, showCategory = 10, aes (NES, fct_reorder (Description, NES), fill = qvalue)) + 
  geom_col() + 
  geom_vline (xintercept = 0, linetype = "dashed", color = "blue", size = 1) + 
  scale_fill_gradientn (colours = c ("#b3eebe","#46bac2","#371ea3"), guide = guide_colorbar (reverse = TRUE)) + 
  scale_x_continuous (expand = c(0, 0)) + 
  theme_bw() +
#theme(text=element_text(size=8))+
  xlab("Normalized Enrichment Score") +
  ylab(NULL) +
ggtitle("GSEA with KEGG")

# Bar plot for filtered GSEA results
ggplot (gsea_go1_2, aes (x = NES, y = fct_reorder (Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline (xintercept = 0, linetype = "dashed", size = 1) +
  scale_fill_gradient (guide = guide_colorbar(reverse = TRUE)) +
  theme_bw () +
  xlab ("Norm Enrich Score") +
  ylab (NULL) +
  ggtitle ("GSEA GO")
```


```{r HvUM_DF }


## GSEA using gene sets from GO pathways
gsea_go2 <- gseGO (geneList = foldchanges2,
                  OrgDb = org.At.tair.db,
                  ont = "ALL",
                  keyType ="ENTREZID",
                  seed = TRUE)

# View the first few entries of the sorted list
#head(H_gene_list_sorted)

# Plot GSEA results
enrichplot::gseaplot2(gsea_go2, geneSetID = c(1:2))
enrichplot::upsetplot(gsea_go2)

# Filter GSEA results based on normalized enrichment score (NES)
gsea_go2_1 <- filter(gsea_go2, NES > 1.95 | NES < -2)
dim(gsea_go2_1)

# Upset plot for filtered GSEA results
enrichplot::upsetplot(gsea_go2_1, n = 10)

# Bar plot for filtered GSEA results
ggplot(gsea_go2_1, aes(x = NES, y = fct_reorder(Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1) +
  scale_fill_gradient(guide = guide_colorbar(reverse = TRUE)) +
  theme_bw() +
  xlab("Norm Enrich Score") +
  ylab(NULL) +
  ggtitle("GSEA GO")
```

```{r}


gsea_go3 <- gseGO( #change num
  geneList = gene_list_sorted3, #change num
  ont = "ALL",
  minGSSize = 3,
  maxGSSize = 800,
  pvalueCutoff = 0.05,
  nPermSimple = 10000,
  verbose = TRUE,
  OrgDb = org.At.tair.db,
  pAdjustMethod = "none"
)

# View the first few entries of the sorted list
#head(H_gene_list_sorted)

# Plot GSEA results
enrichplot::gseaplot2(gsea_go3, geneSetID = c(1:2))
enrichplot::upsetplot(gsea_go3)

# Filter GSEA results based on normalized enrichment score (NES)
gsea_go1_3 <- filter(gsea_go3, NES > 1.95 | NES < -2)
dim(gsea_go1_3)

# Upset plot for filtered GSEA results
enrichplot::upsetplot(gsea_go1_3, n = 10)

# Bar plot for filtered GSEA results
ggplot(gsea_go1_3, aes(x = NES, y = fct_reorder(Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1) +
  scale_fill_gradient(guide = guide_colorbar(reverse = TRUE)) +
  theme_bw() +
  xlab("Norm Enrich Score") +
  ylab(NULL) +
  ggtitle("GSEA GO")
```




```{r}
ptgse1 <- pairwise_termsim(gsea_go1)
ptgse2 <- pairwise_termsim(gsea_go2)
ptgse3 <- pairwise_termsim(gsea_go1_3)

dotplot(ptgse3)
```

```{r}
mlist <- list ( ptgse1, ptgse2, ptgse3)
test_list <- as.matrix (mlist)
names (mlist) <- c( "H down HvUM" , "H down HvIM/UM" ,"H down HvIM" )
mresult <- merge_result (mlist)

dotplot (mresult, 
         showCategory = 12, 
         font.size = 14,
         label_format = 70) + scale_size_continuous(range = c(1,7)) + ggtitle("GO Enrichment of H down Regulated Genes")
#ggsave("./SumData/2_GO_SUM_UP_v1.pdf",width=16, height =16) 


```



```{r}
foldchange <- thedata1 %>%
  select(symbol, log2FoldChange) %>%
  distinct(symbol, .keep_all = TRUE) %>%
  rename(geneSymbol = symbol)
# View a few rows of foldChange to verify geneSymbol column
print(head(foldchange))
```


```{r}
# Compare gene symbols between plot_data and fold hange
cnetplot(s_eGO1,
                 showCategory = 3,  # Adjust as needed
                 color.params = list(foldChange = foldchange$log2FoldChange, category = "purple"),
                 cex.params = list(gene_label = 0.12, category_label = 12),
                 shadowtext = 'gene') +
  ggplot2::theme(legend.position = "right",
                 text = element_text(size = 12))
```


```{r}
# Convert ENTREZID to Gene Symbols
entrez_to_symbol <- AnnotationDbi::select(org.At.tair.db, keys = as.character(s_eGO1@gene), keytype = "ENTREZID", columns = "SYMBOL")
entrez_to_symbol <- unique(entrez_to_symbol)  # Remove duplicates if any

# Join the gene symbols with the eGO1 result
eGO1_with_symbols <- s_eGO1
eGO1_with_symbols@gene <- entrez_to_symbol$SYMBOL 
entrez_to_symbol$symbol[match(as.character(s_eGO1@gene), entrez_to_symbol$entrez)]

cnetplot(eGO1_with_symbols,
                 showCategory =2,  # Adjust as needed
                 color.params = list(foldChange = foldchange$log2FoldChange, category = "purple"),
                 cex.params = list(gene_label = 0.12, category_label = 12),
                 shadowtext = 'gene') +
  ggplot2::theme(legend.position = "right",
                 text = element_text(size = 12))
``````{r}
# Create cnetplot with reduced categories and adjusted cex.params
cnetplot(eGO1,
         showCategory = 6,  # Further limit to top 6 categories
         color.params = list(foldChange = foldchange, category = "purple"),
         cex.params = list(gene_label = 0.12, category_label = 0.02),  # Further adjusted label sizes
         shadowtext = 'gene') +
  ggplot2::theme(legend.position = "right",
                 text = element_text(size = 12))  # Adjust text size
```


```{r}
# Placeholder for other datasets
# thedata2 # HvUM_HUP
# thedata3 # HvIMUP

# DOWN
# thedata4 # IMvUM_IMDWN
# thedata5 # HvUM_HDWN
# thedata6 # HvIMDOWN
```



```{r GSEA}
# Perform GSEA on the up regulated gene data
gsea_go1 <- gseGO(
  geneList = thedata1_tb,
  OrgDb = org.At.tair.db,
  ont = "ALL",
  keyType = "SYMBOL",
  seed = TRUE
)
```

```{r}
# Plot GSEA results
enrichplot::gseaplot2(gsea_go1, geneSetID = c(1:2))
enrichplot::upsetplot(gsea_go1)

# Filter GSEA results based on normalized enrichment score (NES)
gsea_go1_1 <- filter(gsea_go1, NES > 1.95 | NES < -2)
dim(gsea_go1_1)

# Upset plot for filtered GSEA results
enrichplot::upsetplot(gsea_go1_1, n = 10)

# Bar plot for filtered GSEA results
ggplot(gsea_go1_1, aes(x = NES, y = fct_reorder(Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1) +
  scale_fill_gradient(guide = guide_colorbar(reverse = TRUE)) +
  theme_bw() +
  xlab("Norm Enrich Score") +
  ylab(NULL) +
  ggtitle("GSEA GO")

```




```{r DOTPLO}
mlist <- list (s_eGO1, s_eGO2, s_eGO3)
names (mlist) <- c ("IM v UM", "H v UM", "H v IM")
mresult <- merge_result (mlist)

dotplot(mresult, 
         showCategory = 8, 
         font.size = 14,
         label_format = 70) + scale_size_continuous (range = c(1,10)) + ggtitle("sGO ORA Enrichment of UP Regulated Genes")
#ggsave("./SumData/2_sGO_SUM_UP_V1.pdf",width=16, height =16)
```



```{r}
# View the first few entries of the sorted list
#head(H_gene_list_sorted)

# Perform Gene Set Enrichment Analysis (GSEA) using GO terms
gse3 <- gseGO( #change num
  geneList = gene_list_sorted, #change num
  ont = "ALL",
  minGSSize = 3,
  maxGSSize = 800,
  pvalueCutoff = 0.05,
  nPermSimple = 10000,
  verbose = TRUE,
  OrgDb = org.At.tair.db,
  pAdjustMethod = "none"
)
#ptgse1 <- pairwise_termsim(gse1)
#ptgse2 <- pairwise_termsim(gse2)
ptgse3 <- pairwise_termsim(gse3)

dotplot(ptgse3)

mlist <- list ( ptgse1, ptgse2, ptgse3)
test_list <- as.matrix (mlist)
names (mlist) <- c( "H down HvUM" , "H down HvIM/UM" ,"H down HvIM" )
mresult <- merge_result (mlist)

dotplot (mresult, 
         showCategory = 12, 
         font.size = 14,
         label_format = 70) + scale_size_continuous(range = c(1,7)) + ggtitle("GO Enrichment of H down Regulated Genes")
#ggsave("./SumData/2_GO_SUM_UP_v1.pdf",width=16, height =16) 
```


```{r IM V UM UP}


cnetplot (s_eGO1,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted1, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO1, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted1,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "red", high = "navy", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
         axis.text.y = element_text (size = 0),
         axis.text.x = element_text (angle = 60, hjust = 1, size = 12))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: IM UP IM v UM LFC Distribution of Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_IMvUMup.pdf",width=16, height =16)
```

```{r H v UM UP}

cnetplot (s_eGO2,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted2, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'),
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO2, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted2,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "red", high = "navy", name = "Fold Change") +
  theme (panel.grid.major = element_blank (), 
         axis.text.y = element_text (size = 0), 
         axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: H v UM LFC Distribution of Up Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvUMup.pdf",width=16, height =16)
```

```{r H v IM . UM UP}


cnetplot (s_eGO3,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted3, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO3, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted3,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "red", high = "navy", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: H v IM/UM LFC Distribution of Up Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvIMumUP.pdf",width=16, height =16)
```

```{r H v IM UP}


cnetplot (s_eGO3.5,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list (foldChange = gene_list_sorted3.5, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO3.5, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted3.5,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "red", high = "navy", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("GO: H v IM LFC Distribution of Up Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvIMup.pdf",width=16, height =16)
```

```{r DOW}
mlist1 <- list (s_eGO4, s_eGO5, s_eGO6)
names (mlist1) <- c("IM v UM" , "H v UM" ,"H v IM")
mresult1 <- merge_result (mlist1)

dotplot (mresult1, 
         showCategory = 8, 
         font.size = 16,
         label_format = 70) + scale_size_continuous (range = c (1,10)) + ggtitle ("sGO Enrichment of DOWN Regulated Genes")
#ggsave("./SumData/2_sGO_SUM_DOWN_V1.pdf", width = 16, height = 16) 
```


```{r IM V UM DOWN}


cnetplot (s_eGO4,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted4, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO4, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted4,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "navy", high = "red", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
         axis.text.y = element_text (size = 0),
         axis.text.x = element_text (angle = 60, hjust = 1, size = 12))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: IM v UM LFC Distribution of DOWN Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_IMvUMdown.pdf",width=16, height =16)
```


```{r H v UM DOWN}


cnetplot (s_eGO5,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted5, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'),
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO5, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted5,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "navy", high = "red", name = "Fold Change") +
  theme (panel.grid.major = element_blank (), 
         axis.text.y = element_text (size = 0), 
         axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: H v UM LFC Distribution of DOWN Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvUMdown.pdf",width=16, height =16)
```

```{r H v IM . UM}


cnetplot (s_eGO6,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 6,  # Adjust
         layout = "kk",
         color.params = list ( foldChange = gene_list_sorted6, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO6, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted6,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "navy", high = "red", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: H v IM/UM LFC Distribution of DOWN Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvIMumDOWN.pdf",width=16, height =16)
```

```{r}


cnetplot (s_eGO6.5,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list (foldChange = gene_list_sorted6.5, edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (s_eGO6.5, 
         showCategory = 10,
         symbol = "rect", 
         foldChange = gene_list_sorted6.5,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "navy", high = "red", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("sGO: H v IM LFC Distribution of DOWN Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_sGO_Heatplot_LFC_genes_HvIMdown.pdf",width=16, height =16)
```

```{r}

DEG_table <- 
  #IMvUM %>%
  #HvUM %>%
  HvIM.UM %>%
  #HvIM %>%
  mutate ( log2FoldChange > 0 ) #UP DONT CHANGE


# Split the data frame into sub-data frames: up/down regulated genes
results_split <- split (DEG_table, DEG_table$`log2FoldChange > 0`)

GSEAsplit <- c (results_split$`TRUE`) #UP
#GSEAsplit <- c (results_split$`FALSE`) #DOWN

GSEAsplit <- as.data.frame (GSEAsplit, row.names = GSEAsplit$entrez)
GSEAsplitclean <- GSEAsplit[!is.na(GSEAsplit$entrez), ] 

# Create a new table with ENTREZ IDs as row names and the matching log2FoldChange values
logfc_table <- data.frame (log2FoldChange = GSEAsplitclean$log2FoldChange)
rownames (logfc_table) <- GSEAsplitclean$entrez

# Sort the gene list by decreasing LFC
logfc_table_sorted <- logfc_table [order (logfc_table$log2FoldChange, decreasing = TRUE), , drop = FALSE]
# Convert LFC to a named numeric vector with ENTREZ IDs as names
gene_list <- setNames (logfc_table$log2FoldChange, rownames (logfc_table))
# Sort the gene list by decreasing LFC
#UP 1 - 3.5 
list_sorted3 <- sort (gene_list, decreasing = TRUE) #CHANGE NUM

#DOWN 4 - 6.5
#list_sorted5 <- sort (gene_list, decreasing = TRUE) #CHANGE NUM

```


```{r GSEA UP}
# Perform GSEA on the up regulated gene data
gsea_go1 <- gseGO(
  geneList = list_sorted1,
  #geneList = list_sorted2,
  #geneList = list_sorted3,
  #geneList = list_sorted3.5,
  OrgDb = org.At.tair.db,
  ont = "ALL",
  keyType = "ENTREZID",
  seed = TRUE
)
```

```{r UP DOTPLOT}
mlist1 <- list (gsea_go1, gsea_go2, gsea_go3, gsea_go3.5)
names (mlist1) <- c("IM v UM" , "H v UM" ,"H v IM/UM" ,"H v IM")
mresult1 <- merge_result (mlist1)

dotplot (mresult1, 
         showCategory = 8, 
         font.size = 16,
         label_format = 70) + scale_size_continuous (range = c (1,7)) + ggtitle ("GSEA Enrichment of UP Regulated Genes")
#ggsave("./SumData/2_GSEA_SUM_UP.pdf", width = 16, height = 16) 
```

```{r}
cnetplot (
  #gsea_go1,
  #gsea_go2,
  #gsea_go3,
  gsea_go3.5,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list (foldChange = 
                                #list_sorted1,
                              #list_sorted2,
                              #list_sorted3,
                              list_sorted3.5,
                              edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (
  #gsea_go1,
  #gsea_go2,
  #gsea_go3,
  gsea_go3.5,
         showCategory = 10,
         symbol = "rect", 
         foldChange = 
    #list_sorted1,
    #list_sorted2,
    #list_sorted3,
    list_sorted3.5,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "red", high = "navy", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("GSEA: H v IM LFC Distribution of UP Regulated Genes Within Categories")
p2 
#ggsave("./SumData/2_GSEA_HvIM_UP.pdf", width = 16, height = 16) 
```


```{r GSEA DOWN}
# Perform GSEA on the up regulated gene data
gsea_go6.5 <- gseGO(
  #geneList = list_sorted4,
  #geneList = list_sorted5,
  #geneList = list_sorted6,
  geneList = list_sorted6.5,
  OrgDb = org.At.tair.db,
  ont = "ALL",
  keyType = "ENTREZID",
  seed = TRUE
)
```

```{r}
mlist <- list (gsea_go4, gsea_go5, gsea_go6, gsea_go6.5)
names (mlist) <- c("IM v UM" , "H v UM" ,"H v IM/UM" ,"H v IM")
mresult <- merge_result (mlist)

dotplot (mresult, 
         showCategory = 8, 
         font.size = 16,
         label_format = 70) + scale_size_continuous (range = c (1,7)) + ggtitle ("GSEA Enrichment of DOWN Regulated Genes")
#ggsave("./SumData/2_GSEA_SUM_DOWN.pdf", width = 16, height = 16) 
```
```{r DOWN}
cnetplot (
  #gsea_go4,
  #gsea_go5,
  #gsea_go6,
  gsea_go6.5,
         categorySize = "p.adjust", 
         node_label = "category",
         showCategory = 4,  # Adjust
         layout = "kk",
         color.params = list (foldChange = 
                                #list_sorted4,
                              #list_sorted5,
                              #list_sorted6,
                              list_sorted6.5,
                              edge = FALSE, category = "purple", gene = "blue"),
         cex.params = list (category_node = 1, gene_node = 1, gene_label = 1, category_label = 1, shadowtext = 'all'), 
         hilight.params = list (category = NULL, alpha_hilight = 1, alpha_no_hilight = 0.3)) +
  ggplot2::theme (legend.position = "right", text = element_text (size = 12))

p1<- heatplot (
  #gsea_go4,
  #gsea_go5,
  #gsea_go6,
  gsea_go6.5,
         showCategory = 10,
         symbol = "rect", 
         foldChange = 
    #list_sorted4,
    #list_sorted5,
    #list_sorted6,
    list_sorted6.5,
         pvalue = FALSE,
         label_format = 10 ) + 
  scale_fill_continuous (low = "navy", high = "red", name = "Fold Change") + 
  theme (panel.grid.major = element_blank (),
        axis.text.y = element_text (size = 0),
        axis.text.x = element_text (angle = 60, hjust = 1, size = 10))

p2 <- p1 + ggplot2::coord_flip () + 
  ggtitle("GSEA: H v IM LFC Distribution of DOWN Regulated Genes Within Categories")
p2 
ggsave("./SumData/2_GSEA_HvIM_DOWN.pdf", width = 16, height = 16) 
```


```{r}
# Plot GSEA results
enrichplot::gseaplot2(gsea_go1, geneSetID = c(1:2))
enrichplot::upsetplot(gsea_go1)

# Filter GSEA results based on normalized enrichment score (NES)
gsea_go1_1 <- filter(gsea_go1, NES > 1.95 | NES < -2)
dim(gsea_go1_1)

# Upset plot for filtered GSEA results
enrichplot::upsetplot(gsea_go1_1, n = 10)

# Bar plot for filtered GSEA results
ggplot(gsea_go1_1, aes(x = NES, y = fct_reorder(Description, NES), fill = qvalue)) +
  geom_col() +
  geom_vline(xintercept = 0, linetype = "dashed", size = 1) +
  scale_fill_gradient(guide = guide_colorbar(reverse = TRUE)) +
  theme_bw() +
  xlab("Norm Enrich Score") +
  ylab(NULL) +
  ggtitle("GSEA GO")

```

```{r}
#UP
# Remove rows with NA values in the 'entrez' column
#res_clean <- D1down[!is.na(D1down$entrez), ] #1
#res_clean <- D2down[!is.na(D2down$entrez), ] #2
res_clean <- D3down[!is.na(D3down$entrez), ]#3

# Remove rows with NA values in the 'entrez' column
#res_clean <- IMUP[!is.na(IMUP$entrez), ]
#res_clean <- HUP[!is.na(HUP$entrez), ]
#res_clean <- DFUP[!is.na(DFUP$entrez), ]


# Create a new table with ENTREZ IDs as row names and the matching log2FoldChange values
logfc_table <- data.frame(log2FoldChange = res_clean$log2FoldChange)
rownames(logfc_table) <- res_clean$entrez

# View the new table
head(logfc_table)

# Sort the gene list by decreasing log fold change
logfc_table_sorted <- logfc_table[order(logfc_table$log2FoldChange, decreasing = TRUE), , drop = FALSE]

# Convert log2FoldChange to a named numeric vector with ENTREZ IDs as names
gene_list <- setNames(logfc_table$log2FoldChange, rownames(logfc_table))

# Sort the gene list by decreasing log2FoldChange
gene_list_sorted <- sort(gene_list, decreasing = TRUE)


# View the first few entries of the sorted list
#head(H_gene_list_sorted)

# Perform Gene Set Enrichment Analysis (GSEA) using GO terms
gse3 <- gseGO( #change num
  geneList = gene_list_sorted, #change num
  ont = "ALL",
  minGSSize = 3,
  maxGSSize = 800,
  pvalueCutoff = 0.05,
  nPermSimple = 10000,
  verbose = TRUE,
  OrgDb = org.At.tair.db,
  pAdjustMethod = "none"
)
#ptgse1 <- pairwise_termsim(gse1)
#ptgse2 <- pairwise_termsim(gse2)
ptgse3 <- pairwise_termsim(gse3)

dotplot(ptgse3)
```
```{r}
mlist <- list ( ptgse1, ptgse2, ptgse3)
test_list <- as.matrix (mlist)
names (mlist) <- c( "H HvUM" , "H HvIM/UM" ,"H HvIM" )
mresult <- merge_result (mlist)

dotplot (mresult, 
         showCategory = 12, 
         font.size = 14,
         label_format = 70) + scale_size_continuous(range = c(1,7)) + ggtitle("GO Enrichment of H down Regulated Genes")
#ggsave("./SumData/2_GO_SUM_DOWN_v1.pdf",width=16, height =16) 
```


```



