---
title: "3.3_KEGG_Functional_Analysis"
output: html_notebook
---


```{r}
### INSTALLING PACKAGES ###
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install(c("readr", "tidyverse", "org.At.tair.db", "pathview"))


setwd("~/Desktop/Lab/Working_Projects/trapseq_2023")
# Clean environment
rm(list = ls(all.names = TRUE)) # will clear all objects including hidden objects
gc() # free up memory and report the memory usage
options(max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and scientific notation

suppressPackageStartupMessages(library("org.At.tair.db"))
library(clusterProfiler) #A universal enrichment tool for interpreting omics data #prettydoc
library(readr)
library(tidyverse) #to use distinct in line 52
library(pathview)
```


```{r DOWN REGULATED INFECTED MESOPHYLL}
IMdwn<- read_table("dwnLFC1_01_IM.csv", col_names = TRUE) 
IMdwn_tb <- data.frame(IMdwn, row.names = IMdwn$Row.names ) 

###add information to table
IMdwn_tb$symbol = mapIds(org.At.tair.db,
                    keys= IMdwn_tb$Row.names,
                    keytype= "TAIR",
                    column= "SYMBOL",
                    multiVals= "first")
IMdwn_tb$entrez = mapIds(org.At.tair.db,
                    keys=IMdwn_tb$Row.names,
                    keytype="TAIR",
                    column="ENTREZID",
                    multiVals="first")

###clean up table: remove columns, add column names, remove all genes with na values, and duplicate genes
IMdwn_tb <- IMdwn_tb [ ,-c(4:5)] %>% 
  data.frame() %>% 
  as_tibble() %>% 
  na.omit() %>%
  distinct(symbol, .keep_all = TRUE) %>%  
  arrange(desc(UMVsIM_log2FoldChange))

dwnIM_genes<- IMdwn_tb$entrez #Create a list of genes 
```


```{r IM dwn KEGG}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')

# sort the list in decreasing order (required for clusterProfiler)
kegg_dwnIM_list = sort(dwnIM_genes, decreasing = TRUE)

#KEGG Enrichment Analysis of a gene set. Given a vector of genes, this function will return the enrichment KEGG categories with FDR control.
#ora with kegg data base
ora_dwnIM_kegg <- enrichKEGG(gene = kegg_dwnIM_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_dwnIM_kegg)

ora_dwnIM_kegg_modules <- enrichMKEGG(gene =kegg_dwnIM_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           # min size of genes annotated by Ontology term for testing.
                                         maxGSSize = 500,          # max size of genes annotated for testing
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_dwnIM_kegg)
#browseKEGG(ora_analysis_kegg, 'ath00195')
#library("pathview")
#ath04145 <- pathview(gene.data  = dwnIM_genes, pathway.id = "ath00195", species    = "ath")

# create a simple dotplot graph
dotplot(ora_dwnIM_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")

```

```{r UP REGULATED INFECTED MESOPHYLL KEGG}
IMup<- read_table("upLFC1_01_IM.csv",  col_names = TRUE)
IMup_tb <- data.frame(IMup, row.names = IMup$Row.names ) 

IMup_tb$symbol = mapIds(org.At.tair.db, 
                    keys= IMup_tb$Row.names, 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")
IMup_tb$entrez = mapIds(org.At.tair.db, 
                    keys=IMup_tb$Row.names, 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")

IMup_tb <- IMup_tb [ ,-c(4:5)] %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() %>%
  distinct(symbol, .keep_all = TRUE) %>% 
  arrange(desc(UMVsIM_log2FoldChange))

upIM_genes<- IMup_tb$entrez
```

```{r IM dw KEGG}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')

kegg_upIM_list = sort(upIM_genes, decreasing = TRUE)

ora_upIM_kegg <- enrichKEGG(gene = kegg_upIM_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) 
head(ora_upIM_kegg)

ora_upIM_kegg_modules <- enrichMKEGG(gene =kegg_upIM_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,
                                         maxGSSize = 500, 
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_upIM_kegg)

#browseKEGG(ora_analysis_kegg, 'ath00195')
#library("pathview")
#ath04145 <- pathview(gene.data  = dwnIM_genes, pathway.id = "ath00195", species    = "ath")

# create a simple dotplot graph
dotplot(ora_upIM_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```

```{r DOWN REGULATED HAUST CELLS}
Hdwn<- read_table("downLFC1_0.01_H.csv", col_names = TRUE)
Hdwn_tb <- data.frame(Hdwn, row.names = Hdwn$Row.names) 


Hdwn_tb$symbol = mapIds(org.At.tair.db, 
                    keys= Hdwn_tb$Row.names, 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")
Hdwn_tb$entrez = mapIds(org.At.tair.db, 
                    keys=Hdwn_tb$Row.names, 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")


Hdwn_tb <- Hdwn_tb[ ,-c(2:3)] %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() %>%
  distinct(symbol, .keep_all = TRUE) %>% 
  arrange(desc(UMVsH_log2FoldChange))

Hdwn_genes<- Hdwn_tb$entrez
```

```{r H dwn KEGG}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')

kegg_Hdwn_list = sort(Hdwn_genes, decreasing = TRUE)

ora_dwnH_kegg <- enrichKEGG(gene = kegg_Hdwn_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) 
head(ora_dwnH_kegg)

ora_dwnH_kegg_modules <- enrichMKEGG(gene =kegg_Hdwn_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,         
                                         maxGSSize = 500,    
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_dwnH_kegg)
#browseKEGG(ora_analysis_kegg, 'ath00195')
#library("pathview")
#ath04145 <- pathview(gene.data  = dwnIM_genes, pathway.id = "ath00195", species    = "ath")

dotplot(ora_dwnH_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```


```{r UP REG Haustoriated Cells}
Hup<- read_table( "upLFC1_0.01_H.csv", col_names = TRUE)
Hup_tb <- data.frame(Hup, row.names = Hup$Row.names)

Hup_tb$symbol = mapIds(org.At.tair.db, 
                    keys= Hup_tb$Row.names, 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")
Hup_tb$entrez = mapIds(org.At.tair.db, 
                    keys=Hup_tb$Row.names, 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")

Hup_tb <- Hup_tb[ ,-c(2:3)] %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() %>%
  distinct(symbol, .keep_all = TRUE) %>% 
  arrange(desc(UMVsH_log2FoldChange))

upH_genes<- Hup_tb$entrez
```


```{r H UP KEGG}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')

kegg_upH_list = sort(upH_genes, decreasing = TRUE)

#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_upH_kegg <- enrichKEGG(gene = kegg_upH_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_upH_kegg)
#view(ora_upH_kegg)

ora_upH_kegg_modules <- enrichMKEGG(gene =kegg_upH_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_upH_kegg)

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

# create a simple dotplot graph
dotplot(ora_upH_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```


```{r testing}

```


```{r}

mlist<-list(ora_dwnIM_kegg,ora_dwnH_kegg)
names(mlist)<-c("IM (dwn) -enrich","H (down) -enrich")
mresult<-merge_result(mlist)
dotplot(mresult,showCategory=5)

```
```{r}
mlist<-list(ora_upIM_kegg,ora_upH_kegg,ora_dwnIM_kegg,ora_dwnH_kegg)
names(mlist)<-c("IM (up) -enrich","H (up) -enrich","IM (dwn) -enrich","H (down) -enrich")
mresult<-merge_result(mlist)
dotplot(mresult,showCategory=10)

ggsave("dotplot_test.png",width=10, height =9) 
```


```{r read in all diff genes}
library(tibble)
library(tidyverse)
df <- read_table(file = "fulltable_desq.txt")
ALL_DEG <- data.frame(df, row.names = df$Row.names )
geneID<- ALL_DEG$Row.names
```

```{r}
## Prepare deg results -----------------------------------------------
library(dplyr)
###add information to table
ALL_DEG$symbol = mapIds(org.At.tair.db, 
                    keys= row.names(ALL_DEG), 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")

ALL_DEG$entrez = mapIds(org.At.tair.db, 
                    keys=row.names(ALL_DEG), 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")

IM_DEG_table <- ALL_DEG %>% mutate(diffexpressed = case_when(
  UMVsIM_log2FoldChange > 1 &   UMVsIM_padj < 0.05 ~ 'IM_UP',
  UMVsIM_log2FoldChange < 1 &   UMVsIM_padj < 0.05 ~ 'IM_DOWN',
  UMVsIM_padj > 0.05 ~ 'NO'))
  
H_DEG_table <- ALL_DEG %>% mutate(diffexpressed = case_when(
    UMVsH_log2FoldChange > 1 & UMVsH_padj < 0.05 ~ 'H_UP',
    UMVsH_log2FoldChange < 1 & UMVsH_padj < 0.05 ~ 'H_DOWN',
    UMVsH_padj > 0.05 ~ 'NO'))

# Remove non-significant genes
IM_DEG_table <- IM_DEG_table[IM_DEG_table$diffexpressed != 'NO', ]
H_DEG_table <- H_DEG_table[H_DEG_table$diffexpressed != 'NO', ]

# Substitute names so they are annotated nicely in the heatmap later
unique(IM_DEG_table$diffexpressed)
unique(IM_DEG_table$diffexpressed)

IM_DEG_table <- IM_DEG_table %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() 
#%>% arrange(desc(log2FoldChange))
H_DEG_table <- H_DEG_table %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() 

# Split the dataframe into a list of sub-dataframes: upregulated, downregulated genes
IM_results_list <- split(IM_DEG_table, IM_DEG_table$diffexpressed)
H_results_list <- split(H_DEG_table, H_DEG_table$diffexpressed)


IMdown_genes<- IM_results_list$IM_DOWN$entrez
IMup_genes<- IM_results_list$IM_UP$entrez
Hdown_genes<-H_results_list$H_DOWN$entrez
Hup_genes<-H_results_list$H_UP$entrez

kegg_IMdown_list = sort(IMdown_genes, decreasing = TRUE)
kegg_IMup_list = sort(IMup_genes, decreasing = TRUE)
kegg_Hdown_list = sort(Hdown_genes, decreasing = TRUE)
kegg_Hup_list = sort(Hup_genes, decreasing = TRUE)
```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_IMdown_kegg <- enrichKEGG(gene = kegg_IMdown_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_IMdown_kegg)
#view(ora_upH_kegg)

ora_IMdown_kegg_modules <- enrichMKEGG(gene =kegg_IMdown_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_IMdown_kegg)

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

# create a simple dotplot graph
dotplot(ora_IMdown_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_IMup_kegg <- enrichKEGG(gene = kegg_IMup_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_IMup_kegg)
#view(ora_upH_kegg)

ora_IMup_kegg_modules <- enrichMKEGG(gene =kegg_IMup_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_IMup_kegg)

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

# create a simple dotplot graph
dotplot(ora_IMup_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```
```{r}

search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_Hup_kegg <- enrichKEGG(gene = kegg_Hup_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_Hup_kegg)
#view(ora_upH_kegg)

ora_Hup_kegg_modules <- enrichMKEGG(gene =kegg_Hup_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_Hup_kegg)

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

# create a simple dotplot graph
dotplot(ora_Hup_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_Hdown_kegg <- enrichKEGG(gene = kegg_Hdown_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_Hup_kegg)
#view(ora_upH_kegg)

ora_Hdown_kegg_modules <- enrichMKEGG(gene =kegg_Hdown_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)
ggplot(ora_Hdown_kegg)

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

# create a simple dotplot graph
dotplot(ora_Hdown_kegg, 
    color = "qvalue", 
    showCategory = 5, 
    size = "Count")
```

```{r}
mlist<-list(ora_upIM_kegg,ora_upH_kegg,ora_dwnIM_kegg,ora_dwnH_kegg)
names(mlist)<-c("IM (up) -enrich","H (up) -enrich","IM (dwn) -enrich","H (down) -enrich")
mresult<-merge_result(mlist)
dotplot(mresult,showCategory=10)

ggsave("dotplot_test.png",width=10, height =9) 
```

