---
title: "3.3_KEGG_Functional_Analysis"
output: html_notebook
---


```{r}
### INSTALLING PACKAGES ###
#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install(c("readr", "tidyverse", "org.At.tair.db", "pathview"))

setwd("~/Desktop/Lab/Working_Projects/trapseq_2023")
# Clean environment
rm(list = ls(all.names = TRUE)) # will clear all objects including hidden objects
gc() # free up memory and report the memory usage
options(max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and keep scientific notation

suppressPackageStartupMessages(library("org.At.tair.db"))
library(clusterProfiler) #A universal enrichment tool for interpreting omics data #prettydoc?
library(readr)
library(tidyverse) #to use distinct in line 52
library(pathview)
library(enrichplot)
```


```{r read in all diff genes}
library(tibble)
library(tidyverse)
df <- read_table(file = "fulltable_desq.txt")
ALL_DEG <- data.frame(df, row.names = df$Row.names )
geneID<- ALL_DEG$Row.names
```

```{r}
## Prepare deg results -----------------------------------------------
library(dplyr)
###add information to table
ALL_DEG$symbol = mapIds(org.At.tair.db, 
                    keys= row.names(ALL_DEG), 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")

ALL_DEG$entrez = mapIds(org.At.tair.db, 
                    keys=row.names(ALL_DEG), 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")

pad = 0.05

IM_DEG_table <- ALL_DEG %>% mutate(diffexpressed = case_when(
  UMVsIM_log2FoldChange > 1 &   UMVsIM_padj < pad ~ 'IM_UP',
  UMVsIM_log2FoldChange < 1 &   UMVsIM_padj < pad ~ 'IM_DOWN',
  UMVsIM_padj > pad ~ 'NO'))
  
H_DEG_table <- ALL_DEG %>% mutate(diffexpressed = case_when(
    UMVsH_log2FoldChange > 1 & UMVsH_padj < pad ~ 'H_UP',
    UMVsH_log2FoldChange < 1 & UMVsH_padj < pad ~ 'H_DOWN',
    UMVsH_padj > pad ~ 'NO'))

# Remove non-significant genes
IM_DEG_table <- IM_DEG_table[IM_DEG_table$diffexpressed != 'NO', ]
H_DEG_table <- H_DEG_table[H_DEG_table$diffexpressed != 'NO', ]

# Substitute names so they are annotated nicely in the heatmap later
unique(IM_DEG_table$diffexpressed)
unique(H_DEG_table$diffexpressed)

IM_DEG_table <- IM_DEG_table %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() 
#%>% arrange(desc(log2FoldChange))
H_DEG_table <- H_DEG_table %>% 
  data.frame()  %>% 
  as_tibble() %>% 
  na.omit() 

# Split the dataframe into a list of sub-dataframes: upregulated, downregulated genes
IM_results_list <- split(IM_DEG_table, IM_DEG_table$diffexpressed)
H_results_list <- split(H_DEG_table, H_DEG_table$diffexpressed)


IMdown_genes<- IM_results_list$IM_DOWN$entrez
IMup_genes<- IM_results_list$IM_UP$entrez
Hdown_genes<-H_results_list$H_DOWN$entrez
Hup_genes<-H_results_list$H_UP$entrez

```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')

kegg_IMdown_list = sort(IMdown_genes, decreasing = TRUE)
kegg_IMup_list = sort(IMup_genes, decreasing = TRUE)
kegg_Hdown_list = sort(Hdown_genes, decreasing = TRUE)
kegg_Hup_list = sort(Hup_genes, decreasing = TRUE)

#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_IMdown_kegg <- enrichKEGG(gene = kegg_IMdown_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = pad,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_IMdown_kegg)
#view(ora_upH_kegg)

ora_IMdown_kegg_modules <- enrichMKEGG(gene =kegg_IMdown_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = pad)
```



```{r}
# Simple dotplot 
dotplot(ora_IMdown_kegg, 
    color = "qvalue", 
    showCategory = 10, 
    x = "Count")
#plotEnrich(ego, plot_type="gotangram", sim_method="Rel")
#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

#edox2<-pairwise_termsim(ora_IMdown_kegg)
#p1<-treeplot(edox2)
#p2<-treeplot(edox2, hclust_method="average")
#aplot::plot_list(p1,p2, tag_levels='A')

#upsetplot(ora_IMdown_kegg) #For over-representation analysis,upsetplot will calculate the overlaps among different gene sets. ForGSEA result, it will plot the foldchange distributions of different categories (e.g. unique to pathway, overlaps among different pathways).

```




```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_IMup_kegg <- enrichKEGG(gene = kegg_IMup_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = pad,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_IMup_kegg)
#view(ora_upH_kegg)

ora_IMup_kegg_modules <- enrichMKEGG(gene =kegg_IMup_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = pad)
```


```{r}
# Simple dotplot 
dotplot(ora_IMup_kegg, 
    color = "qvalue", 
    showCategory = 10, 
    x = "Count")

#browseKEGG(ora_upH_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

edox2<-pairwise_termsim(ora_IMup_kegg)
p1<-treeplot(edox2)
p2<-treeplot(edox2, hclust_method="average")
aplot::plot_list(p1,p2, tag_levels='A')

upsetplot(ora_IMup_kegg) #For over-representation analysis,upsetplot will calculate the overlaps among different gene sets. ForGSEA result, it will plot the foldchange distributions of different categories (e.g. unique to pathway, overlaps among different pathways).

```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_Hup_kegg <- enrichKEGG(gene = kegg_Hup_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = pad,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_Hup_kegg)
#view(ora_upH_kegg)

ora_Hup_kegg_modules <- enrichMKEGG(gene =kegg_Hup_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = pad)
```


```{r}
# Simple dotplot 
dotplot(ora_Hup_kegg, 
    color = "qvalue", 
    showCategory = 10, 
     x="Count")

#browseKEGG(ora_Hup_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

edox2<-pairwise_termsim(ora_Hup_kegg)
p1<-treeplot(edox2)
p2<-treeplot(edox2, hclust_method="average")
aplot::plot_list(p1,p2, tag_levels='A')

upsetplot(ora_Hup_kegg) #For over-representation analysis,upsetplot will calculate the overlaps among different gene sets. ForGSEA result, it will plot the foldchange distributions of different categories (e.g. unique to pathway, overlaps among different pathways).
```

```{r}
search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


#ora with kegg data base.  using enrichKEGG() is a shortcut for doing ORA using KEGG
ora_Hdown_kegg <- enrichKEGG(gene = kegg_Hdown_list,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = pad,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_Hdown_kegg)
#view(ora_Hdown_kegg)

ora_Hdown_kegg_modules <- enrichMKEGG(gene =kegg_Hdown_list,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           
                                         maxGSSize = 500,          
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = pad)
```


```{r}
# Simple dotplot 
dotplot(ora_Hdown_kegg, 
    color = "qvalue", 
    showCategory = 10,
    x="count", 
   # size = "Count"
    )

#browseKEGG(ora_Hdown_kegg, 'ath04626')
#library("pathview")
#ath04626 <- pathview(gene.data  = kegg_upH_list, pathway.id = "ath04626", species    = "ath")

edox2<-pairwise_termsim(ora_Hdown_kegg)
p1<-treeplot(edox2)
p2<-treeplot(edox2, hclust_method="average")
aplot::plot_list(p1,p2, tag_levels='A')

upsetplot(ora_Hdown_kegg) #For over-representation analysis,upsetplot will calculate the overlaps among different gene sets. ForGSEA result, it will plot the foldchange distributions of different categories (e.g. unique to pathway, overlaps among different pathways).
```

```{r}
mlist<-list(ora_IMup_kegg,ora_Hup_kegg,ora_IMdown_kegg,ora_Hdown_kegg)
names(mlist)<-c("IM (up) -enrich","H (up) -enrich","IM (dwn) -enrich","H (down) -enrich")
mresult<-merge_result(mlist)
dotplot(mresult,showCategory=15, font.size=10)
#The dotplot shows the number of genes associated with the first 50 terms (size/show category) and the p-adjusted values for these terms (color). This plot displays the top 50 genes by gene ratio (# genes related to GO term / total number of sig genes), not p-adjusted value.here k is the number of genes participating in the current KEGG pathway (within top-40, top-80, or other top lists), and n is the number of genes (also within top-40, top-80, or other top lists) annotated as participants of any KEGG pathway (these numbers are provided in the brackets in the bottom of the figure). Dot color indicates the enrichment test FDR (Fisher's exact test).

#ggsave("dotplot_p05.png",width=16, height =16) 
```

```{r}

```

