---
title: "3_Functional_Analysis_Notebook"
output: html_notebook
---



```{r}
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install(c("AnnotationHub", "ensembldb", "tidyverse", "readr")) 


```


```{r}
setwd("~/Desktop/Lab/Working_Projects/trapseq_2023")
library(readr)
OG_DEGFILE<- read_delim(file="deg_analysis_DESeq_all.csv", delim = ",")
nrow(OG_DEGFILE)

deg_table <- data.frame(OG_DEGFILE, row.names = OG_DEGFILE$row )#gene ids stored as row names
geneID<- OG_DEGFILE$row
deg_table <- deg_table[ ,-c(1:2)]
```



```{r}
library(biomartr) 
library(tidyverse)

biomartr::organismBM(organism = "Arabidopsis thaliana")

arabido_attributes = 
  biomartr::organismAttributes("Arabidopsis thaliana") %>% 
  filter(dataset == "athaliana_eg_gene")
arabido_attributes

attributes_to_retrieve = c("tair_symbol", "entrezgene_id")

result_BM <- biomartr::biomart( genes      = OG_DEGFILE$row,                  # genes were retrieved using biomartr::getGenome()
                                mart       = "plants_mart",                     # marts were selected with biomartr::getMarts()
                                dataset    = "athaliana_eg_gene",               # datasets were selected with biomartr::getDatasets()
                                attributes = attributes_to_retrieve,            # attributes were selected with biomartr::getAttributes()
                                filters =   "ensembl_gene_id" )# query key
head(result_BM)
```

```{r}
# building the universe!
library(readr)
allgenes <- read_table("featcount.txt", 
                        col_names = TRUE, skip = 1)
read.count <- data.frame(allgenes, row.names = allgenes$Geneid ) #gene ids stored as row names
all_arabidopsis_genes <- (read.count$Geneid) # directly selects the gene column

# we want the correspondence of TAIR/Ensembl symbols with NCBI Entrez gene ids
attributes_to_retrieve = c("tair_symbol", "uniprotswissprot","entrezgene_id")

# Query the Ensembl API
all_arabidopsis_genes_annotated <- biomartr::biomart(genes = all_arabidopsis_genes,
                                                     mart       = "plants_mart",                 
                                                     dataset    = "athaliana_eg_gene",           
                                                     attributes = attributes_to_retrieve,        
                                                     filters =  "ensembl_gene_id" )  

# for compatibility with enrichGO universe
# genes in the universe need to be characters and not integers (Entrez gene id)
all_arabidopsis_genes_annotated$entrezgene_id = as.character(
  all_arabidopsis_genes_annotated$entrezgene_id) 
```
```{r}
library(clusterProfiler)
# retrieving NCBI Entrez gene id for our genes called differential
diff_arabidopsis_genes_annotated <- biomartr::biomart(genes = geneID,
                                                     mart       = "plants_mart",                 
                                                     dataset    = "athaliana_eg_gene",           
                                                     attributes = attributes_to_retrieve,        
                                                     filters =  "ensembl_gene_id" )  

```


```{r}
library("biomartr")
library("clusterProfiler")
library("tidyverse")
library("enrichplot")
suppressPackageStartupMessages(library("org.At.tair.db"))
library("biomaRt")  # only use to remove cache bug

# performing the ORA for Gene Ontology Biological Process class
ora_analysis_bp <- enrichGO(gene = diff_arabidopsis_genes_annotated$entrezgene_id, 
                            universe = all_arabidopsis_genes_annotated$entrezgene_id, 
                            OrgDb = org.At.tair.db,  # contains the TAIR/Ensembl id to GO correspondence for A. thaliana
                            keyType = "ENTREZID",
                            ont = "BP",              # either "BP", "CC" or "MF",
                            pAdjustMethod = "BH",
                            pvalueCutoff  = 0.05,
                            qvalueCutoff  = 0.01,
                            readable = TRUE, 
                            pool = FALSE)

# clusterProfiler::simplify to disambiguate which simplify() function you want to use
ora_analysis_bp_simplified <- clusterProfiler::simplify(ora_analysis_bp) 
```


```{r}
write_delim(x = as.data.frame(ora_analysis_bp_simplified@result), 
            path = "go_results.tsv", 
            delim = "\t")

# have a look at a few columns and rows
ora_analysis_bp_simplified@result[1:5,1:8]
```


```{r}
dotplot(ora_analysis_bp_simplified)
```


```{r}
library("enrichplot")
ora_analysis_bp <- pairwise_termsim(ora_analysis_bp, method = "JC")
emapplot(ora_analysis_bp, color = "qvalue")
```


```{r}
library("biomartr")
library("clusterProfiler")
library("tidyverse")
library("enrichplot")
suppressPackageStartupMessages(library("org.At.tair.db"))
library("biomaRt")  # only use to remove cache bug


search_kegg_organism('ath', by='kegg_code')
search_kegg_organism('Arabidopsis thaliana', by='scientific_name')


ora_analysis_kegg <- enrichKEGG(gene = diff_arabidopsis_genes_annotated$entrezgene_id,
                                universe = all_arabidopsis_genes_annotated$entrezgene_id,
                                organism = "ath",
                                keyType = "ncbi-geneid",
                                minGSSize = 10,
                                maxGSSize = 500,
                                pAdjustMethod = "BH",
                                qvalueCutoff = 0.01,
                                use_internal_data = FALSE) # force to query latest KEGG db
head(ora_analysis_kegg)
ora_analysis_kegg_modules <- enrichMKEGG(gene = diff_arabidopsis_genes_annotated$entrezgene_id,
                                         universe = all_arabidopsis_genes_annotated$entrezgene_id,
                                         organism = "ath",
                                         keyType = "ncbi-geneid",
                                         minGSSize = 10,           # minimal size of genes annotated by Ontology term for testing.
                                         maxGSSize = 500,          # maximal size of genes annotated for testing
                                         pAdjustMethod = "BH",
                                         qvalueCutoff = 0.01)

browseKEGG(ora_analysis_kegg, 'ath04145')
library("pathview")
ath04145 <- pathview(gene.data  = all_arabidopsis_genes_annotated$entrezgene_id,
                     pathway.id = "ath04145",
                     species    = "ath")
#ggplot(ora_analysis_kegg)
```


```{r}
# create a simple dotplot graph
dotplot(ora_analysis_kegg, 
    color = "qvalue", 
    showCategory = 10, 
    size = "Count")

```

```{r}
suppressPackageStartupMessages(library("org.At.tair.db"))
library(enrichplot)
library(DOSE)
library(pathview)
library(clusterProfiler)
library(AnnotationHub)
library(ensembldb)
library(tidyverse)


#convert gene symbers to ID

#if (!require("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install(c("AnnotationDbi", "org.At.tair.db", "pathview", "gageData"))

#library(AnnotationDbi)
#library(org.At.tair.db)
#class(org.At.tair.db)
#columns(org.At.tair.db)

#print(res05)
library(readr)
#OG_DEGFILE<- read_delim(file="deg_analysis_DESeq_all.csv", delim = ",")
#nrow(OG_DEGFILE)


ALL_DEG<- read.csv(file = "deg_analysis_DESeq_all.csv")
ALL_DEG <- data.frame(ALL_DEG, row.names = ALL_DEG$row )#gene ids stored as row names
geneID<- ALL_DEG$row
#deg_table <- deg_table[ ,-c(1:2)]

ALL_DEG$symbol = mapIds(org.At.tair.db, 
                    keys= row.names(ALL_DEG), 
                    keytype= "TAIR" , 
                    column= "SYMBOL", 
                    multiVals= "first")

ALL_DEG$entrez = mapIds(org.At.tair.db, 
                    keys=row.names(ALL_DEG), 
                    keytype="TAIR", 
                    column="ENTREZID", 
                    multiVals="first")

deg_table2 <- ALL_DEG[ ,-c(1:2)]

non_duplicates <- which(!duplicated(deg_table2$symbol))
deg_table2 <- deg_table2[non_duplicates, ]
```

```{r}
ALL_DEG_tb <- ALL_DEG[ ,-c(1:2)] %>%
data.frame() %>%
rownames_to_column(var="gene") %>%
as_tibble()

w = which(ALL_DEG_tb$gene%in% deg_table2$symbol)
res_ids = ALL_DEG_tb[w,]
m = match(res_ids$gene, deg_table2$symbol)
res_ids$ensgene = deg_table2$entrez[m]
```

```{r}
#oRA

## background set of ensgenes
allOE_genes <- ALL_DEG_tb$entrez
sigOE = dplyr::filter(ALL_DEG_tb, padj < 0.05)
sigOE_genes = sigOE$entrez

#Now we can perform the GO enrichment analysis and save the results:
## Run GO enrichment analysis
ego <- enrichGO(gene = sigOE_genes,
universe = allOE_genes,
keyType = "ENTREZID",
OrgDb = org.At.tair.db,
ont = "BP",
pAdjustMethod = "BH",
qvalueCutoff = 0.05,
readable = TRUE)

## Output results from GO analysis to a table
cluster_summary <- data.frame(ego)
write.csv(cluster_summary, "clusterProfiler_oe.csv")

dotplot(ego, showCategory=50)
```

```{r}
pwt <- pairwise_termsim(ego,
                        method = "JC",
                        semData = NULL,
                        showCategory = 50)
emapplot(pwt, showCategory = 50)
```
```{r}
## To color genes by log2 fold changes, we need to extract the log2 fold changes from o
OE_foldchanges <- sigOE$log2FoldChange
names(OE_foldchanges) <- sigOE$gene

## Cnetplot details the genes associated with one or more terms - by default gives the
cnetplot(ego,
         categorySize="pvalue",
         showCategory = 5,
         foldChange=OE_foldchanges,
         vertex.label.font=6)

## If some of the high fold changes are getting drowned out due to a large range, you c
OE_foldchanges <- ifelse(OE_foldchanges > 2, 2, OE_foldchanges)
OE_foldchanges <- ifelse(OE_foldchanges < -2, -2, OE_foldchanges)
cnetplot(ego,
         categorySize="pvalue",
         showCategory = 5,
         foldChange=OE_foldchanges,
         vertex.label.font=6)
```

```{r}
## Subsetting the ego results without overwriting original `ego` variable
ego2 <- ego
ego2@result <- ego@result[c(1,3,4,8,9),]
## Plotting terms of interest
cnetplot(ego2,
         categorySize="pvalue",
         foldChange=OE_foldchanges,
         showCategory = 5,
         vertex.label.font=6)
```
```{r}
# Gene set enrichment analysis (GSEA)
m = match(res_ids$ensgene,deg_table2$gene)
res_ids$entrez = deg_table2$entrez[m]
## remove any NA values
wna = which(is.na(res_ids$entrez))
res_entrez = res_ids[-wna,]
## remove any Entrez duplicates
res_entrez <- res_entrez[which(duplicated(res_entrez$entrez) == F), ]
wdup = which(!duplicated(res_entrez$entrez))
res_entrez=res_entrez[wdup,]
```

```{r}
## Extract the foldchanges
foldchanges <- res_entrez$log2FoldChange
## Name each fold change with the corresponding Entrez ID
names(foldchanges) <- res_entrez$entrez
```

```{r}
## Sort fold changes in decreasing order
foldchanges <- sort(foldchanges, decreasing = TRUE)
head(foldchanges)
```

```{r}
# GSEA using gene sets associated with BP Gene Ontology terms
gseaGO <- gseGO(geneList = foldchanges,
OrgDb = org.At.tair.db,
ont = 'BP',
nPerm = 1000,
minGSSize = 20,
pvalueCutoff = 0.05,
verbose = FALSE)
gseaGO_results <- gseaGO@result
gseaplot(gseaGO, geneSetID = 'GO:0007423')
```

```{r}
library(GSEABase)
# Load in GMT file of gene sets (we won't download it from the Broad Institute [website](http://sc2 <- read.gmt("data/c2.all.v2023.1.Hs.entrez.gmt")
msig <- GSEA(foldchanges, TERM2GENE=c2, verbose=FALSE)
msig_df <- data.frame(msig)
```

