---
title: "1_Diagnostics_DEG_Notebook"
output: 
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---
# ICM 2024MAY15 DESeq2 Script
# UM v IM v H

```{r CODE CHUNK 1 CLEAR}
# Clean environment
rm (list = ls (all.names = TRUE)) # will clear all objects including hidden objects
gc () # free up memory and report the memory usage
options (max.print = .Machine$integer.max, scipen = 0, stringsAsFactors = F, dplyr.summarise.inform = F) # avoid truncated output in R console and keep scientific notation
```


```{r CHUNK 2 Packages}
# Remove hashtags to install any missing packages
#if (!require("BiocManager", quietly = TRUE))
 #   install.packages("escape")
#Install all
#BiocManager::install(c( "corrplot", "dendextend","readr","DESeq2", "ggrepel", "ggplot2", "pheatmap", "devtools", "ggforce","pheatmap", "gplots", "RColorBrewer", "ggdendro","enrichplot", "magrittr","dplyr","tibble", "tidyverse", "ComplexHeatmap", "escape")) 
#install one
#BiocManager::install(c("VennDetail"))

# Set the working directory to your project folder
setwd("~/Desktop/Lab/Working_Projects/R_trapseq_2023")
# Load necessary packages
suppressPackageStartupMessages({
  library(DESeq2)
  library(readr)
  library(tidyverse)
  library(enrichplot)
  #library(dplyr)
  #library(tibble)
  #library(magrittr)
  library(gplots)
  library(RColorBrewer)
  #library(corrplot)
#  library(ggdendro)
  library(dendextend)
  library(ggplot2)
  library(ggrepel)
  library(pheatmap)
  library(xlsx)
#  library(escape)
  library(clusterProfiler)
  library(org.At.tair.db)
  library(reshape2)
library(apeglm)
})


# Read in raw count data from txt file 
featcount <- read_table ("./RawData/featcount.txt", col_names = TRUE, skip = 1)
read.count <- data.frame (featcount, row.names = featcount$Geneid)  # Set gene IDs as row names
read.count <- read.count [, -c(1:6)]  # Remove columns not related to gene counts
# Rename columns for consistency
orig_names <- names (read.count)  # Backup original names
colnames (read.count) <- c ("IT-107", "IT-108", "IT-109", "IT-110", "H-107", "H-108", "H-109", "H-110", "H-111", "UT-106", "UT-108", "UT-114", "IT-206", "IT-207", "IT-208", "IT-209", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UT-204", "UT-208", "UT-213", "UT-214", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215")
```



```{r CHUNK 6 Set Variables}
# Modifying for our purposes 
ImvHvUM <- read.count [ ,-c(1:4,10:16,22:25)]

#Variables
sample_info_UM <- data.frame(
  Sample = c ( "H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  Groups = c ( "H", "H", "H", "H", "H", "IM", "IM", "IM", "IM", "IM", "UM", "UM", "UM", "UM", "UM"),
  Condition = c ("Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Infected", "Uninfected", "Uninfected", "Uninfected", "Uninfected", "Uninfected"),
  Replicate = c ("H-107", "H-108", "H-109", "H-110", "H-111", "IM-206", "IM-207", "IM-208", "IM-209", "IM-210", "UM-204", "UM-208", "UM-213", "UM-214", "UM-215"),
  row.names = "Sample") 

sample_info_UM$Groups <- as.factor (sample_info_UM$Groups)
all (rownames (sample_info_UM) %in% colnames (ImvHvUM)) 
#if "false" something is wrong
```


```{r Data Matrix}
# Create a DESeqDataSet object from the matrix of counts and column metadata  

data_set <- DESeqDataSetFromMatrix (countData = ImvHvUM, 
                               colData = sample_info_UM, 
                               design = ~ Groups)

# Prefilter
data_set <- data_set [rowSums (counts (data_set)) > 10, ]
# Set control group
data_set$Groups <- relevel (data_set$Groups, ref = "UM")

```

```{r Normalization}
# Perform variance stabilizing transformation (VST) for visualization and clustering
vsd <- vst (data_set)
colnames (vsd) <- sample_info_UM$Replicate 
norm.counts <- assay (data_set) #%>%
#   as.data.frame() %>% rownames_to_column (., var = "rowname")

#write.csv (norm.counts, file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_normalized.csv", quote = FALSE, row.names = TRUE)

#write.xlsx(as.data.frame(norm.counts), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_normalized.xlsx", sheetName = "normalized", col.names = TRUE, row.names = FALSE, append = FALSE)
```


```{r}
sim_mat <- ImvHvUM [rowSums (ImvHvUM) >= 1, ]
cor_samps <- round (cor (sim_mat, method = "spearman"), digits = 2)
melted_cor_samps <- melt(cor_samps)
ggheatmap <- ggplot (data = melted_cor_samps, aes (x = Var1, y = Var2, fill = value)) + 
  geom_tile() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 12, hjust = 1)) +
  theme(axis.text.y = element_text(size = 12))
ggheatmap <- ggheatmap + 
  geom_text(aes(Var2, Var1, label = value), color = "white", size = 4) +
theme(
  axis.title.x = element_blank(),
  axis.title.y = element_blank(),
  panel.grid.major = element_blank(),
  panel.border = element_blank(),
  panel.background = element_blank(),
  axis.ticks = element_blank())
ggheatmap


library(brew)
# Calculate sample distances and create hierarchical clustering
sample_dist <- norm.counts [complete.cases (norm.counts), ] 
correlation_matrix <- cor (sample_dist, method = "spearman")
dist_matrix <- as.dist (1 - correlation_matrix)

# Hierarchical clustering
clustering_result <- hclust (dist_matrix, method = "complete")
dendrogram_object <- as.dendrogram (clustering_result) %>% color_branches (k = 3)
 
# Plot dendrogram
plot (dendrogram_object, type = "rectangle", ylab = "Height", main = "VST Read Counts - Distance: Spearman Correlation")
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_DistMat_clusters.pdf")

# Create heatmap of distance matrix using pheatmap package  
DistMatrix <- as.matrix (dist_matrix)
rownames (DistMatrix) <- paste (vsd$Replicate, sep = "-")
colnames (DistMatrix) <- paste (vsd$Replicate, sep = "-")
color_scheme <- colorRampPalette (rev (brewer.pal (9, "Blues")))(255)

pheatmap (DistMatrix, clustering_distance_rows = dist_matrix, clustering_distance_cols = dist_matrix, 
         color = color_scheme, main = "Sample Distance Matrix Heatmap")

#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_DistMatrix.pdf")
```




```{r DESEQ2}
results_object <- DESeq (data_set)  # Perform DE analysis
res <- results (results_object)  # Extract Complete results
```

```{r}
#summary(res)
#names(res)
#mcols(res)
#reOrdered<-res[order(res$padj),]
#resultsNames(results_object)
```


```{r}

#vsd<-varianceStabilizingTransformation(results_object, blind=TRUE)

select <- order (rowMeans (counts (results_object, normalized = FALSE)), decreasing = TRUE)#[1:100]
norm.res <- normTransform (results_object) # defaults to log2(x+1)
log2.norm.res <- assay (norm.res)[select,]
```

```{r}
pp4 <-pheatmap(assay(vsd)[select,])
#install.packages('ggheatmap')
library(ggheatmap)

pp5<-ggheatmap(assay(vsd)[select,])
pp5
```


```{r}

d <- plotCounts(results_object, 
                 gene = "AT1G21890", 
                 intgroup = "Groups", 
                 returnData = TRUE)

# Create plot with jittered points and gene labels
ggplot (d, aes (x = Groups, y = count, color = Groups)) +
  geom_point (position = position_jitter (w = 0.1, h = 0)) +
  geom_text_repel (aes (label = rownames (d))) +
  theme_bw () +
  ggtitle ("AT1G21890 Expression") +
  theme (plot.title = element_text (hjust = 0.5))
#ggsave("./SumData/1_Diag_DEG/1_countData_AT1G21890.pdf")

```

```{r}
# PCA principle component analysis, visualize the similarities and differences between *samples*
pc_data <- plotPCA (vsd, intgroup = c( "Replicate" , "Groups" ), returnData = TRUE) 
percentVar <- round (100 * attr (pc_data, "percentVar" ))

p <- ggplot (pc_data, aes(PC1, PC2, label = Replicate, colour = Groups)) +
  geom_point (aes (shape = Groups), size = 4) + scale_color_manual (values = c( "red", "forestgreen", "blue" )) +
   theme_classic()

p2 <- p + geom_text_repel (box.padding = 1, cex = 3, max.overlaps = 30, segment.linetype = 2) + labs (title = "PCA of VST Normalized Gene Counts" ) +
  xlab(paste0 ( "PC1: ", percentVar[1], "% variance" )) +
  ylab(paste0 ( "PC2: ", percentVar[2], "% variance" ))
p2
#ggsave("./SumData/1_Diag_DEG/1_PCA_Final_IMVUMVH_v2.pdf", width = 6, height = 6)
```


```{r}
#resultsNames (results_object)
resHUM <- results (results_object, contrast = c("Groups", "H", "UM"), independentFiltering = TRUE, alpha = 0.05, pAdjustMethod = "BH", parallel = TRUE)
resIMUM <- results (results_object, contrast = c("Groups", "IM", "UM"), independentFiltering = TRUE, alpha = 0.05, pAdjustMethod = "BH", parallel = TRUE)


#Using LFC shrinkage to compare genes by L2FC
lfcHUM <- lfcShrink(results_object, coef = "Groups_H_vs_UM", type = "apeglm")
lfcIMUM <- lfcShrink(results_object, coef = "Groups_IM_vs_UM", type = "apeglm")

lfcHUM = lfcHUM[order(lfcHUM$padj, na.last = NA), ]
lfcIMUM = lfcIMUM[order(lfcIMUM$padj, na.last = NA), ]
alpha = 0.05
```

```{r}
lfcHUM_tbl <- as_tibble(lfcHUM, rownames = "Gene_ID") %>% 
  mutate(group = "HvUM") 

lfcIMUM_tbl <- as_tibble(lfcIMUM, rownames = "Gene_ID") %>% 
    mutate(group = "IMvUM")

resHUM_tbl <- as_tibble(resHUM, rownames = "Gene_ID") %>% 
  mutate(group = "resHUM")
resIMUM <- as_tibble(resIMUM, rownames = "Gene_ID") %>% 
  mutate(group = "resIMUM")
```


```{r}
all_lfc <- lfcHUM_tbl %>% 
  inner_join(lfcIMUM_tbl, by = "Gene_ID") 

all_lfc <- all_lfc %>% 
  dplyr::select(-pvalue.x, -pvalue.y) %>% 
  mutate(
    L2FC_HUM = log2FoldChange.x,
    L2FC_IMUM = log2FoldChange.y,
    padj_HUM = padj.x,
    padj_IMUM = padj.y,
  ) #%>% view()

#view(all_lfc)

lfcHUM_tbl %>% 
  ggplot(aes(log2FoldChange, -log(padj, 10))) +
  geom_point() 

lfcIMUM_tbl %>% 
  ggplot(aes(log2FoldChange, -log(padj, 10))) +
  geom_point() 
```

```{r}
lfc_long <- all_lfc %>% 
  dplyr::select(1, 12:13) %>% 
  pivot_longer(
    cols = -Gene_ID,
    names_to = c("LF2C", "Groups"),
    names_sep = "_",
    values_to = c("Expression")
)
#view(lfc_long)
pval_long <- all_lfc %>% 
  dplyr::select(1, 14:15) %>% 
  pivot_longer(
    cols = -Gene_ID,
    names_to = c("adjp", "Groups"),
    names_sep = c("_"),
    values_to = c("Pvalue")
)
#view(pval_long)
exp_tbl <- inner_join(lfc_long, pval_long) %>%
  dplyr::select(-LF2C, -adjp) #%>% view()
```


```{r}
exp_tbl <- exp_tbl %>% 
  mutate(
    ExpSig = case_when (Expression >= log(2) & Pvalue <= 0.05 ~ "Up-regulated",
                           Expression <= -log(2) & Pvalue <= 0.05 ~ "Down-regulated",
                           TRUE ~ "Unchanged")
    )# %>% view()

exp_tbl1 <- exp_tbl [exp_tbl$ExpSig != 'Unchanged', ] 
```


```{r}
exp_tbl %>%   ggplot(aes(Groups, Expression)) +
  geom_boxplot() +
  theme_bw() +
  xlab("Treatment") 
```

```{r}
transporter_list<-readxl::read_xlsx("./RawData/6_transporter_df.xlsx")

submod1 = exp_tbl1 %>%
  subset (exp_tbl1$Gene_ID %in% transporter_list$TAIR) %>%
  as_tibble() %>% 
  na.omit() 

submod1_split <- split (submod1, submod1$Groups)
HUM<- c (submod1_split$HUM)
HUM_df <- as.data.frame (HUM, row.names = HUM$Gene_ID)

#submod1 <- submod1 [submod1$ExpSig != 'Unchanged', ] # Remove non-significant genes
```



```{r}
set.seed(123)
significantly_different_genes = res %>%
   as.data.frame() %>%
   filter (padj < 0.05) %>%
  filter (abs (log2FoldChange) >= 1) #%>% write.csv("./DerivedData/1_DEG_HvIMvUM_padj05LCF1.csv") 

#Order genes by p.value and Extract Gene Names with the desired adjusted p-value cut-off
DGE.results.sorted <- significantly_different_genes [order (significantly_different_genes$padj), ]
DGEgenes <- rownames (subset (DGE.results.sorted, padj < 0.05))[1:2000]
hm.mat_DGEgenes <- norm.counts [DGEgenes, ]


pheatmap_differential_expression <- pheatmap (hm.mat_DGEgenes, show_rownames = FALSE, angle_col = c( "45" ), color = colorRampPalette (rev (brewer.pal (n = 7, name = "RdYlBu")))(100), 
            cluster_rows = TRUE,
            clustering_distance_rows = "correlation", 
           # cluster_cols = TRUE,
           # clustering_distance_cols = "correlation", 
            clustering_method = "complete", 
            scale = "row",
           main = "Top 2000 Differentially Expressed Genes(padj<0.05, LFC≥1)"
           #, cutree_cols = 2, 
            #cutree_rows = 2#, 
          #  kmeans_k = 2
  )
#dev.copy2pdf(file="./SumData/1_Diag_DEG/1_hmap_IMvHvUM_2000.pdf")
```


```{r H v UM DEGS}
# Map TAIR IDs to ENTREZ IDs
#exp_tbl$entrez <- mapIds (org.At.tair.db, keys = exp_tbl$Gene_ID, keytype = "TAIR", column = "ENTREZID", multiVals = "first") 
exp_tbl$symbol <- mapIds (org.At.tair.db, keys = exp_tbl$Gene_ID, keytype = "TAIR", column = "SYMBOL", multiVals = "first")
pad=0.05

#H_DEG_table <- H_DEG_table [H_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
#unique (H_DEG_table$diffexpressed)
#write.csv (H_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_HvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)

# Split the data frame into sub-data frames: up/down regulated genes
results_split <- split (exp_tbl, exp_tbl$Groups)
HUM<- c (results_split$HUM)
HUM_df <- as.data.frame (HUM, row.names = HUM$Gene_ID)

IMUM <- c (results_split$IMUM)
IMUM_df <- as.data.frame (IMUM, row.names = IMUM$Gene_ID)

#write.xlsx(as.data.frame(H_DF), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_nofilter.xlsx", sheetName = "HvUM", col.names = TRUE, row.names = FALSE, append = FALSE)
```


```{r IM V UM DEG}
UMVsIM <- results (results_object, c('Groups', 'IM', 'UM'))

# Map TAIR IDs to ENTREZ IDs
UMVsIM$entrez <- mapIds(org.At.tair.db, keys = row.names(UMVsIM), keytype = "TAIR", column = "ENTREZID", multiVals = "first")
UMVsIM$symbol <- mapIds (org.At.tair.db, keys = row.names (UMVsIM), keytype = "TAIR", column = "SYMBOL", multiVals = "first")

IM_DF <- UMVsIM %>% as.data.frame() %>% rownames_to_column (., var = "rowname") %>% as_tibble() %>%  na.omit()

#write.csv(IM_DF, file = "./DerivedData/1_Diag_DEG/1_DEG_IMvUM_NoFilters.csv", quote = FALSE, row.names = TRUE)
 
IM_DEG_table <- IM_DF %>% mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'IM_UP',
  log2FoldChange < -1 &   padj < pad ~ 'IM_DOWN',
  padj > pad ~ 'NO' )) %>%  na.omit()

IM_DEG_table <- IM_DEG_table [IM_DEG_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
unique (IM_DEG_table$diffexpressed)

#write.csv(IM_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_IMvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)
 
# Split the data frame into a list of sub-data frames: up-regulated, down regulated genes
IM_results_split <- split (IM_DEG_table, IM_DEG_table$diffexpressed)
IMDOWN <- c(IM_results_split$IM_DOWN)
IMDOWN <- as.data.frame (IMDOWN, row.names = IMDOWN$entrez)
IMUP <- c (IM_results_split$IM_UP)
IMUP <- as.data.frame (IMUP, row.names = IMUP$entrez)

#write.csv (IMUP, file = "./DerivedData/1_Diag_DEG/1_DEG_IMUP_LFC1p05.csv", quote = FALSE, row.names = TRUE)

#write.xlsx(as.data.frame(IM_DF), file = "./DerivedData/1_Diag_DEG/1_HvIMvUM_nofilter.xlsx", sheetName = "IMvUM", col.names = TRUE, row.names = FALSE, append = TRUE)
```


```{r H Vs IM}
#length (H_DF$rowname) <- length (HvIM.UM$rowname)
ven <- VennDetail::venndetail (list (HvsUM = HUM_df$Gene_ID, IMvsUM = IMUM_df$Gene_ID))
plot(ven, type = "venn", order = TRUE, textsize = 3)
plot(ven, type = "venn", col = c("orchid", "#d95f02"), sep = "_",
mycol = c("orchid", "#d95f02"), cat.cex = 1.5, alpha = 0.5, cex = 2,
cat.fontface = "bold", margin = 0.05, text.scale = c(1.5, 1.5), filename = NULL, piecolor = NULL,
revcolor = "blue", any = NULL, show.number = TRUE,
show.x = TRUE, log = FALSE, base = NULL, percentage = FALSE,
sets.x.label = "Set Size", mainbar.y.label = "Intersection Size",
nintersects = 40, abbr = TRUE, abbr.method = "both.sides",
minlength = 3)
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_Upset_IMvHvUM.pdf")
ven

HUM_venlist<- as.data.frame(VennDetail::getSet(ven, "HvsUM"))
IMUM_venlist<- as.data.frame(VennDetail::getSet(ven, "IMvsUM"))
#VennDetail::make.subset(ven, "HvsUM")
VennDetail::result(ven)
VennDetail::vennpie(ven)
```



```{r CODE CHUNK 9 DEG NUmbers}
plotMA (results_object, alpha = 0.01)
plotMA (results_object, alpha = 0.05)

#to see how many genes are < to 0.05
table (results_object$padj < 0.05) 
print (results_object)

#to see how many genes are < to 0.001
table (results_object$padj < 0.01) 
print (results_object)
```


```{r}
#length (H_DF$rowname) <- length (HvIM.UM$rowname)
ven <- VennDetail::venndetail (list (HvsUM = H_DEG_table$rowname, IMvsUM = IM_DEG_table$rowname, HvsIM = HIMum_DEG_table$rowname))
plot(ven, type = "venn", order = TRUE, textsize = 3)
plot(ven, type = "venn", col = c("#1b9e77", "#d95f02", "orchid3"), sep = "_",
mycol = c("#1b9e77", "#d95f02", "orchid3"), cat.cex = 1.5, alpha = 0.5, cex = 2,
cat.fontface = "bold", margin = 0.05, text.scale = c(1.5, 1.5, 1.5), filename = NULL, piecolor = NULL,
revcolor = "blue", any = NULL, show.number = TRUE,
show.x = TRUE, log = FALSE, base = NULL, percentage = FALSE,
sets.x.label = "Set Size", mainbar.y.label = "Intersection Size",
nintersects = 40, abbr = TRUE, abbr.method = "both.sides",
minlength = 3)
#dev.copy2pdf(file = "./SumData/1_Diag_DEG/1_Upset_IMvHvUM.pdf")

```


```{r}
VennDetail::detail(ven)
VennDetail::dplot(ven)

HIM_venlist<- as.data.frame(VennDetail::getSet(ven, "HvsIM"))
VennDetail::make.subset(ven, "HvsIM")
VennDetail::result(ven)
VennDetail::vennpie(ven)
```

```{r}
HIM_detail<- as.data.frame(HIM_venlist, row.names = HIM_venlist$Detail)

HIM_detail$ENTREZ = mapIds (org.At.tair.db, keys = row.names (HIM_detail) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

HIM_detail$symbol <- mapIds (org.At.tair.db, keys = row.names (HIM_detail), keytype = "TAIR", column = "SYMBOL", multiVals = "first")

#write.csv(HIM_detail, file= "./DerivedData/1_Diag_DEG/1_HIM_167uniq.csv", quote=F, row.names=FALSE)


HIM_LFC_uniq <- HIMum_DEG_table %>%
  subset (HIMum_DEG_table$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 

HIM_LFC_uniq2 <- IM_DF %>%
  subset (IM_DF$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 

HIM_LFC_uniq3 <- H_DF %>%
  subset (H_DF$rowname %in% HIM_detail$Detail) %>%
  as_tibble() %>% 
  na.omit() 


#write.csv(HIM_uniq_genes, file= "./DerivedData/1_Diag_DEG/1_HIM_uniq.csv", quote=F, row.names=FALSE)
```


```{r}
results_object1 <- DESeq(data_set1, betaPrior = FALSE)

res5 <- lfcShrink(results_object, contrast = c('Groups','IM','UM'), res=UMVsIM1, type = 'normal')
res6 <- lfcShrink(results_object, contrast = c('Groups','H','UM'), res=UMVsH1, type = 'normal')
res7 <- lfcShrink(results_object, contrast = c('Groups','H','IM'), res=HvIM.UM, type = 'normal')
```


```{r}
library(EnhancedVolcano)
EnhancedVolcano (HvIM.UM,
    lab = HvIM.UM$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'IMvUM',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)


EnhancedVolcano(IM_DF,
    lab = IM_DF$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'IMvUM',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)

EnhancedVolcano(H_DF,
    lab = H_DF$rowname,
    x = 'log2FoldChange',
    y = 'pvalue',
     selectLab =  c('AT1G02010'),
     xlab = bquote(~Log[2]~ 'fold change'),
     xlim = c(-6, 6),
    title = 'UMvsH',
    pCutoff = 0.05,
    FCcutoff = 1,
    pointSize = 3.0,
    labSize = 6.0,
      shape = c(1, 4, 23, 8),
    col=c('black', 'yellow', 'blue', 'green'),
    colAlpha = 1,
    legendLabels=c('Not sig.','Log (base 2) FC','p-value',
      'p-value & Log (base 2) FC'),
    legendPosition = 'right',
    legendLabSize = 16,
    legendIconSize = 5.0,
    cutoffLineType = 'twodash',
    cutoffLineCol = 'black',
    cutoffLineWidth = 0.8,
    hline = c(0.05),
    hlineCol = c('pink'),
    hlineType = c('solid'),
    hlineWidth = c(1.0),
    gridlines.major = FALSE,
    gridlines.minor = FALSE)
```


```{r}
#if (!requireNamespace("BiocManager", quietly = TRUE))
#    install.packages("BiocManager")

#BiocManager::install("vidger")
```

```{r}
library(vidger)
# DESeq2 example
#hl <- c(atguniq)

FW_df<- vsFourWay(
     x = "H", y = "IM",
     control = "UM", data = results_object,
     d.factor = "Groups", type = "deseq", padj = 0.05,
     x.lim = NULL, y.lim = NULL, lfc = 1, title = TRUE, grid = TRUE,
     legend = TRUE,
     data.return = TRUE, 
     #highlight = hl, 
     xaxis.text.size = 10,
yaxis.text.size = 10, xaxis.title.size = 10, yaxis.title.size = 10,
main.title.size = 10, legend.text.size = 10
)
FW_df
#ggsave("./SumData/1_Diag_DEG/1_LFC_IMVUMVH.pdf", width = 8, height = 8)

# Extract data frame from visualization

df_four <- FW_df$data ## or use tmp$data
#head(df_four)
```

```{r}
color_split <- split (df_four, df_four$color)
green_genes<- c (color_split$green)
green_genes_df <- as.data.frame (green_genes, row.names = green_genes$id)

red_genes<- c (color_split$red)
red_genes_df <- as.data.frame (red_genes, row.names = red_genes$id)
```

```{r}
pad = 0.05
eGO1 <- enrichGO(
  gene = green_genes_df$id, #3
  OrgDb = org.At.tair.db,
  keyType = 'TAIR',
  ont = "ALL",
  pAdjustMethod = "BH",
  qvalueCutoff = pad
)
s_eGO1 <- clusterProfiler::simplify(eGO1)
dotplot (s_eGO1, 
         showCategory = 8, 
         font.size = 14) + scale_size_continuous (range = c(1,10)) + ggtitle("sGO ORA of Green Genes")
#ggsave("./SumData/1_Diag_DEG/1_Green_dotplot.pdf", width = 8, height = 8)


eGO2 <- enrichGO(
  gene = red_genes_df$id, #3
  OrgDb = org.At.tair.db,
  keyType = 'TAIR',
  ont = "ALL",
  pAdjustMethod = "BH",
  qvalueCutoff = pad
)
s_eGO2 <- clusterProfiler::simplify(eGO2)
dotplot (s_eGO2, 
         showCategory = 8, 
         font.size = 14) + scale_size_continuous (range = c(1,10)) + ggtitle("sGO ORA of Red Genes")
#ggsave("./SumData/1_Diag_DEG/1_RED_dotplot.pdf", width = 8, height = 8)

```

```{r}
green_genes_tair<- as.data.frame(green_genes_df, row.names = green_genes_df$id)

green_genes_tair$ENTREZ = mapIds (org.At.tair.db, keys = row.names (green_genes_tair) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )

red_genes_tair<- as.data.frame(red_genes_df, row.names = red_genes_df$id)

red_genes_tair$ENTREZ = mapIds (org.At.tair.db, keys = row.names (red_genes_tair) , keytype = "TAIR" , column = "ENTREZID" , multiVals = "first" )
```


```{r}
ora_kegg1 <- enrichKEGG (gene = green_genes_tair$ENTREZ, #1
  organism = "ath", keyType = "ncbi-geneid", minGSSize = 10, maxGSSize = 500, pAdjustMethod = "BH", qvalueCutoff = pad, use_internal_data = FALSE) # force to use latest KEGG db
ora_kegg2 <- enrichKEGG (gene = red_genes_tair$ENTREZ, #1
  organism = "ath", keyType = "ncbi-geneid", minGSSize = 10, maxGSSize = 500, pAdjustMethod = "BH", qvalueCutoff = pad, use_internal_data = FALSE) # force to use latest KEGG db

edox1 <- pairwise_termsim (ora_kegg1)
edox2 <- pairwise_termsim (ora_kegg2)
dotplot (edox1, showCategory = 12, font.size = 15) + ggtitle("KEGG Enrichment")
```



```{r}
submod1_split <- split (FW_df, FW_df$Groups)

HUM<- c (submod1_split$HUM)
HUM_df <- as.data.frame (HUM, row.names = HUM$Gene_ID)

IMUM<- c (submod1_split$IMUM)
IMUM_df <- as.data.frame (IMUM, row.names = IMUM$Gene_ID)


#test1 <- HUM_df %>% 
#  inner_join(IMUM_df, by = "Gene_ID")

# Spread the data to get separate columns for HUM and IMUM regulation
spread_data <- exp_tbl %>%
  pivot_wider(names_from = Groups, values_from = ExpSig)

# Find genes that are Up in HUM and Down in IMUM
up_hum_down_imum <- spread_data %>% filter(HUM == "Up" & IMUM == "Down")

# Find genes that are Down in HUM and Up in IMUM
down_hum_up_imum <- spread_data %>% filter(HUM == "Down" & IMUM == "Up")



# Print the results
cat("Genes Up in HUM and Down in IMUM:\n")
print(up_hum_down_imum)

cat("\nGenes Down in HUM and Up in IMUM:\n")
print(down_hum_up_imum)
```


```{r}
color_split <- split (df_four, df_four$color)
green_genes<- c (color_split$green)
green_genes_df <- as.data.frame (green_genes, row.names = green_genes$id)

red_genes<- c (color_split$red)
red_genes_df <- as.data.frame (red_genes, row.names = red_genes$id)
```


```{r}
green_transporters = submod1 %>%
  subset (submod1$Gene_ID %in% green_genes_df$id) %>%
  as_tibble() %>% 
  na.omit() 

red_transporters<- submod1 %>%
  subset (submod1$Gene_ID %in% red_genes_df$id) %>%
  as_tibble() %>% 
  na.omit()


green_transporters = green_transporters %>%
  subset (green_transporters$Gene_ID %in% green_genes_df$id) %>%
  as_tibble() %>% 
  na.omit()
```


```{r}

#test1 <- HUM_df %>% 
#  inner_join(IMUM_df, by = "Gene_ID")


red_transporters_df<- as.data.frame(red_transporters, row.names = red_transporters$Gene_ID)
red_transporters_spread<- test1 %>%
  subset (test1$Gene_ID %in% red_transporters_df$Gene_ID) %>%
  as_tibble() %>% 
  na.omit()

#write.xlsx(as.data.frame(red_transporters_spread), file = "./DerivedData/1_red_transporters.xlsx", sheetName = "Unchanged in the H", col.names = TRUE, row.names = FALSE, append = FALSE)

green_transporters_df<- as.data.frame(green_transporters, row.names = green_transporters$Gene_ID)

green_transporters_spread = test1 %>%
  subset (test1$Gene_ID %in% green_transporters_df$Gene_ID) %>%
  as_tibble() %>% 
  na.omit() 

#write.xlsx(as.data.frame(green_transporters_spread), file = "./DerivedData/1_green_transporters.xlsx", sheetName = "Unchanged in the IM", col.names = TRUE, row.names = FALSE, append = FALSE)
```

```{r}
data("results_object")
vsBoxPlot(results_object, d.factor = "Groups", type = c("deseq"),
title = TRUE, legend = TRUE, grid = TRUE, aes = c("violin"), fill.color = NULL,
data.return = FALSE, xaxis.text.size = 10, yaxis.text.size = 10,
xaxis.title.size = 12, yaxis.title.size = 12, main.title.size = 15,
legend.text.size = 10, legend.title.size = 12)

vsDEGMatrix(results_object, padj = 0.05, d.factor = "Groups", type = c(
"deseq"), title = TRUE, legend = TRUE, grid = TRUE,
data.return = FALSE, grey.scale = FALSE, xaxis.text.size = 10,
yaxis.text.size = 10, main.title.size = 15, legend.text.size = 10,
legend.title.size = 12)

vsMAMatrix(results_object, d.factor = "Groups", type = c("deseq"),
padj = 0.05, y.lim = NULL, lfc = NULL, title = TRUE, legend = TRUE,
grid = TRUE, counts = TRUE, data.return = FALSE, xaxis.text.size = 9,
yaxis.text.size = 9, xaxis.title.size = 10, yaxis.title.size = 10,
main.title.size = 15, legend.text.size = 9, facet.title.size = 10)

vsScatterMatrix(results_object, d.factor = "Groups", type = c("deseq"), comp = NULL, title = TRUE, grid = TRUE, man.title = NULL,
data.return = FALSE, xaxis.text.size = 9, yaxis.text.size = 9,
xaxis.title.size = 10, yaxis.title.size = 10, main.title.size = 15,
facet.title.size = 10)

vsVolcanoMatrix(results_object, d.factor = "Groups", type = c("deseq"), padj = 0.05, x.lim = NULL, lfc = NULL, title = TRUE,
legend = TRUE, grid = TRUE, counts = TRUE, data.return = FALSE,
xaxis.text.size = 9, yaxis.text.size = 9, xaxis.title.size = 10,
yaxis.title.size = 10, main.title.size = 15, legend.text.size = 9,
facet.title.size = 10)
```



```{r}

him_uniq<- read_csv("./DerivedData/1_Diag_DEG/1_HIM_uniq.csv")
him_uniq_table <- him_uniq %>% 
  mutate (diffexpressed = case_when (
  log2FoldChange > 1 &   padj < pad ~ 'H_UP',
  log2FoldChange < -1 &   padj < pad ~ 'H_DOWN',
  padj > pad ~ 'NO' ))  %>%  na.omit()

H_DEG_table <- him_uniq_table [him_uniq_table$diffexpressed != 'NO', ] # Remove non-significant genes

# Substitute names so they are annotated nicely in the heat map later
unique (H_DEG_table$diffexpressed)
#write.csv (H_DEG_table, file = "./DerivedData/1_Diag_DEG/1_DEG_HvUM_LFC1p05.csv", quote = FALSE, row.names = TRUE)

# Split the data frame into sub-data frames: up/down regulated genes
H_results_split <- split (H_DEG_table, H_DEG_table$diffexpressed)
HDOWN <- c (H_results_split$H_DOWN)
HDOWN <- as.data.frame (HDOWN, row.names = HDOWN$entrez)
HUP <- c (H_results_split$H_UP)
HUP <- as.data.frame (HUP, row.names = HUP$entrez)
```





